### ISSUE TITLE
Rust failing to read the config file: "Trailing characters after parsing"

### ISSUE THREAD

**Issue by BraindeadBZH** [nextcloud/notify_push#103]
After updating to 0.2.0 the notify_push server does not start anymore and shows the following error:
```
notify_push     | Error:
notify_push     |    0: Failed to parse config
notify_push     |    1: Failed to parse nextcloud config
notify_push     |    2: Error while parsing php literal: Trailing characters after parsing
notify_push     |
notify_push     | Location:
notify_push     |    src/config/nc.rs:7
```

Tried to clean trailing commas from the config file but it changes nothing.

**Comment by icewind1991** [comment]
can you provide your config file (replacing the passwords and other private information of course)

**Comment by BraindeadBZH** [comment]
Here is my config.php

```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'redis',
    'password' => '****',
    'port' => 6379,
  ),
  'instanceid' => '****',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' =>
  array (
    0 => '****.com',
    1 => '****.com',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '21.0.2.1',
  'overwrite.cli.url' => 'https://****.com',
  'overwritehost' => '****.com',
  'overwriteprotocol' => 'https',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****',
  'dbpassword' => '****',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 2,
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => '****.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '****',
  'mail_smtpport' => '587',
  'mail_smtpname' => '****',
  'mail_smtppassword' => '****',
  'default_phone_region' => 'CH',
  'trusted_proxies' =>
  array (
    0 => '172.29.0.0/24',
  ),
);

```

**Comment by icewind1991** [comment]
Hmm, nothing weird there and that parses just fine for me, do any of the redacted strings contain escaped quotes or other "special" characters?

**Comment by BraindeadBZH** [comment]
It does not seem so. The config file was working with 0.1.7, did not touch it since.
I deploy NC using docker-compose, here how I create the notify_push image, if it is of any use:
```
FROM rust:alpine

WORKDIR /app
RUN wget https://github.com/nextcloud/notify_push/releases/download/v0.2.0/notify_push.tar.gz
RUN tar -xzf notify_push.tar.gz
RUN rm -f notify_push.tar.gz

CMD ["/app/notify_push/bin/x86_64/notify_push", "/var/www/html/config/config.php"]
EXPOSE 7867/tcp
```

**Comment by Blackclaws** [comment]
@icewind1991 I tested my config with your config parser and the example code snippet provided and it parses fine. This is exceedingly weird as the error 
```
1: Failed to parse nextcloud config
   2: Error while parsing php literal:  
   2: . |
   2: 2 |   'apps_paths' => array (
   2: 3 |       0 => array (
   2: 4 |               'path'     => OC::$SERVERROOT.'/apps',                                                                               
   2:   |                             ^^ No valid token found, expected one of [Bool, Integer, Float, LiteralString, Null, Array, SquareOpen]
   2: 5 |               'url'      => '/apps',
   2: 6 |               'writable' => false,
   2: 
```
appears to originate from the config parser. Is there maybe some weird version mismatch going on in the released version of the app?

**Comment by Blackclaws** [comment]
I've gone ahead and built notify_push from source inside the nextcloud:21 container after installing rust inside it. The results are that the version that was built from source also doesn't work inside the container. That for me narrows it down to either environment variables inside the container or the general os underlying the container. My local build machine is running arch-linux.

**Comment by Blackclaws** [comment]
I've found a solution that solves this issue. The config.php must NOT be in /var/www/html/config/config.php. Putting it in a different location such as /tmp allows notify push to start. It appears that there is some sort of replacement going on when the config.php is put in /var/www/html/config which then causes parsing to fail.

**Comment by Blackclaws** [comment]
Doing some more debugging on what exactly causes this: If the path passed to notify_push is a path containing some sort of folder structure i.e. something like /var/www/html/config/config.php or even ./config.php it will try to load the whole directory for some reason. 

If the path passed to it is just config.php without any sort of folder slashes and the config.php file is in the current folder then it will parse JUST that single file and run fine as well. So another workaround for those running in containers is to set the workdir to /var/www/html/config and change the arguments to notify_push to just config.php without any folder path.

**Comment by BraindeadBZH** [comment]
@Blackclaws Thank you for your forensic on this, very useful information. I will probably wait for the 0.2.1 as I don't want to screw up my docker-compose for a temporary workaround.

**Comment by icewind1991** [comment]
0.2.1 disables this new behavior by default

**Comment by BraindeadBZH** [comment]
Sorry but it did not solved the issue for me, still getting the same error.

**Comment by raimund-schluessler** [comment]
I also still see this problem with 0.2.1.

@icewind1991 I think the logic is inversed here:
https://github.com/nextcloud/notify_push/blob/aa46e84f5605faf46a6aef2efc71e47cda392ce1/src/config/nc.rs#L7

If `glob` is true, it only does `parse(path)`, and if it is false, it parses globally, no? And since `glob` is `false` by default (I think), it still parses all files.

**Comment by icewind1991** [comment]
0.2.2 should fix the inverted logic

**Comment by raimund-schluessler** [comment]
0.2.2 indeed fixes the inverted logic and does not parse all config files by default now.
