### ISSUE TITLE
Rust failing to read the config file: "No valid token found"

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/notify_push#105]
After updating my notify push server docker container to 0.2.0 it is stuck in a restart loop because it runs into the following error. It feels similar to the problem in #103.

```
notify-push_1  | Error: 
notify-push_1  |    0: Failed to parse config
notify-push_1  |    1: Failed to parse nextcloud config
notify-push_1  |    2: Error while parsing php literal:  
notify-push_1  |    2: . |
notify-push_1  |    2: 2 |   "apps_paths" => array (
notify-push_1  |    2: 3 |       0 => array (
notify-push_1  |    2: 4 |               "path"     => OC::$SERVERROOT."/apps",                                                                               
notify-push_1  |    2:   |                             ^^ No valid token found, expected one of [Bool, Integer, Float, LiteralString, Null, Array, SquareOpen]
notify-push_1  |    2: 5 |               "url"      => "/apps",
notify-push_1  |    2: 6 |               "writable" => false,
notify-push_1  |    2: 
notify-push_1  | 
notify-push_1  | Location:
notify-push_1  |    src/config/nc.rs:7
notify-push_1  | 
notify-push_1  | Backtrace omitted.
notify-push_1  | Run with RUST_BACKTRACE=1 environment variable to display it.
notify-push_1  | Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by snevas** [comment]
```
Error: 
   0: Failed to parse config
   1: Failed to parse nextcloud config
   2: Error while parsing php literal:  
   2: 1 |  array (
   2: 2 |     'mail_smtpmode' => 'smtp',
   2: 3 |     'mail_smtphost' => getenv('SMTP_HOST'),                                                                                   
   2:   |                        ^^ No valid token found, expected one of [Bool, Integer, Float, LiteralString, Null, Array, SquareOpen]
   2: 4 |     'mail_smtpport' => getenv('SMTP_PORT') ?: (getenv('SMTP_SECURE') ? 465 : 25),
   2: 5 |     'mail_smtpsecure' => getenv('SMTP_SECURE') ?: '',
   2: 

Location:
   src/config/nc.rs:7

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```
Same here. Is it because version 0.2.0 is meant for NC22? I am running push & nextcloud-fpm (version 21.0.2) in docker.

**Comment by Blackclaws** [comment]
See: https://github.com/nextcloud/notify_push/issues/103 for the reason why this happens and for a workaround

**Comment by icewind1991** [comment]
0.2.1 disables this new behavior by default

**Comment by snevas** [comment]
> ```
> Error: 
>    0: Failed to parse config
>    1: Failed to parse nextcloud config
>    2: Error while parsing php literal:  
>    2: 1 |  array (
>    2: 2 |     'mail_smtpmode' => 'smtp',
>    2: 3 |     'mail_smtphost' => getenv('SMTP_HOST'),                                                                                   
>    2:   |                        ^^ No valid token found, expected one of [Bool, Integer, Float, LiteralString, Null, Array, SquareOpen]
>    2: 4 |     'mail_smtpport' => getenv('SMTP_PORT') ?: (getenv('SMTP_SECURE') ? 465 : 25),
>    2: 5 |     'mail_smtpsecure' => getenv('SMTP_SECURE') ?: '',
>    2: 
> 
> Location:
>    src/config/nc.rs:7
> 
> Backtrace omitted.
> Run with RUST_BACKTRACE=1 environment variable to display it.
> Run with RUST_BACKTRACE=full to include source snippets.
> ```
> 
> Same here. Is it because version 0.2.0 is meant for NC22? I am running push & nextcloud-fpm (version 21.0.2) in docker.

Rebuilt version 0.2.1, issue is still there. Exactly same output.

**Comment by siccovansas** [comment]
Thanks for the fix! I updated to 0.2.1, but the same problem still exists. Can this issue be opened again?

**Comment by menardorama** [comment]
Same issue on my side, to restore the service I had to pass all the argument on command line ....

**Comment by Crocmagnon** [comment]
I'm experiencing the same issue, do we have a workaround ? If so, would it be possible to push a new version?

**Comment by LittleHuba** [comment]
> do we have a workaround or a fix?

If you are using docker-compose, set the working directory to the directory containing your config and then provide the config file without a path to notify_push.

```
working_dir: /var/www/html/config
entrypoint: /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push config.php
```

**Comment by Crocmagnon** [comment]
> set the working directory to the directory containing your config and then provide the config file without a path to notify_push

I can confirm this workaround fixes the issue for me. Thanks ! 🎉

**Comment by snevas** [comment]
Is there a new requirement that push doesn't work with a sqlite database? With the above suggested workaround I get a new error:
```
/var/www/html/config #  RUST_BACKTRACE=1 RUST_BACKTRACE=full /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push config.php 
Error: 
   0: Failed to parse config
   1: Failed to parse nextcloud config
   2: invalid database configuration: no database name
   3: no database name

Location:
   src/config/nc.rs:8

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                 ⋮ 1 frame hidden ⋮                               
   2: notify_push::config::Config::from_opt::h0eb489de37c2ff10
      at <unknown source file>:<unknown line>
   3: notify_push::main::{{closure}}::hae281d088ca06a36
      at <unknown source file>:<unknown line>
   4: notify_push::main::h40dd060eedd3058a
      at <unknown source file>:<unknown line>
   5: std::sys_common::backtrace::__rust_begin_short_backtrace::hbdb9b8c87ee8610b
      at <unknown source file>:<unknown line>
   6: main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

If this is a separate issue unrelated to this one or the workaround, let me know and I'll open a new issue.
