### ISSUE TITLE
Omitting --glob-config does not prevent notify_push to load other config files

### ISSUE THREAD

**Issue by BraindeadBZH** [nextcloud/notify_push#108]
After moving to 0.2.1 to avoid error during config file parsing, my issue did not disappeared. I, then, decided to remove all other php files from the config folder except config.php and now 0.2.1 is able to start without issue.

**Comment by raulrr1986** [comment]
This solved the problem with push_client ?, I have not understood much the solution, please be more explicit, some screenshots and examples would be appreciated. All my deployment is done in docker.

**Comment by aanno** [comment]
I circumvent the very same problem by (a) using the docker image of `notify_push` and (b) only mounting `config/config.php` into the container, i.e. using the following with `docker-compose`:

```bash
volumes:
      - ./config/config.php:/var/www/html/config/config.php:z,ro
```

**Comment by kinolaev** [comment]
This is because:
- functions `parse` and `parse_glob` https://github.com/icewind1991/nextcloud-config-parser/blob/5cb1eb8/src/nc.rs#L116 are equal
- this condition https://github.com/nextcloud/notify_push/blob/7b84a34/src/config/nc.rs#L7 must be reversed

**Comment by raimund-schluessler** [comment]
I can confirm that 0.2.2. fixes the issue.
