### ISSUE TITLE
notify_push set up correctly, receiving messages, but no refresh in files app (and desktop clients)

### ISSUE THREAD

**Issue by lopezio** [nextcloud/notify_push#114]
Hi All,

I recently updated one Nextcloud instance (comming from 19., over 20, doing all the steps required), to the latest 21 (21.0.3), and - eager to have the high performance files backend - I followed all steps to install the push service, which - generally speaking - **seems to be set up correctly and send notifications**: 

- The rust server is set up (although by cargo building it myself, since the server is a FreeBSD 12.2)
- The rust test_client reports success on all tests (coming from a Linux client)<details><pre>
[unicorn:/tank/misc/notify_push] lopezio% ./target/debug/test_client https://cloud.(redacted domain) redacted_username 'redacted_password'
Found push server at wss://cloud.(redacted domain)/push/ws
Authenticated
Received file update notification
</pre></details>
- On the server, occ notify_push:self-test reports no error. All 6 output messages are positive:<details><pre>
redis is configured
push server is receiving redis messages
push server can load mount info from database
push server can connect to the Nextcloud server
push server is a trusted proxy
push server is running the same version as the app</pre>
</details> 
- In the Browser (Firefox or Chrome), there is an open websocket to the /push/ws URL, which authenticates (sends a string and then gets the response "authenticated"), and when changing a file over other means, the web client receives a "notify_file" string. It stays open and gets all messages, also notify_notification, for example, when issuing an "occ notification:test-push - <username>"
- The websocket events (open/message) seem to be triggered so far in the Firefox debug panel.

**Expected behavior:**
- When a file / folder gets added/changed/deleted, the client(s) supporting push should refresh their listing or the file. 

**Actual behavior**:
- The WebUI does not update the folder to reflect its new content, even if it is open in that moment. Nothing notable in Console either. It never seems to happen actually. Only force reloading the page shows the new content.
- Also, when connecting with an iOS client, latest version, the folder is not updated
- Also, the Desktop client (3.2.4) on MacOS does not react on notify_file pushes, although it seems to get them (at least when starting the notify_push daemon in the foreground and wathing its output with --log-level debug 

Any hints on what could be wrong and/or on which debug information could be useful to debug this behavior? 
Or do I have the wrong expectations? Is it possible that something is still wrong with my websocket setup? 

One note about the server / http setup: The way it's working right now is the following: Haproxy does the SSL termination and passes requests (http 1.1) over to a backend apache, which in turn does the ProxyPass stuff as outlined in the documentation here. I know I could get to the push service directly from haproxy (which is surely the best way), but for configuration management reasons I opted interim for the Apache solution.

I know this issue is possibly better placed somewhere else, because it seems to be more about the clients than about the push server, but my guess here was that I might have good chances here to find someone that knows about what's going on.

Thank You a lot in advance for any hint...!

Lorenzo

**Comment by icewind1991** [comment]
Neither the webinterface nor the mobile clients currently support refreshing the file lists.

Please open an issue in the desktop client repo for that not updating as expected

**Comment by lopezio** [comment]
> Neither the webinterface nor the mobile clients currently support refreshing the file lists.
> 
> Please open an issue in the desktop client repo for that not updating as expected

Sorry for asking back on this closed issue - but what good is the whole push thing if clients ignore the push messages? Is there any client known to act in some way on the notify_file message - just to test? 
We tested with the current macOS Desktop client and nothing happened upon a file change - although the client was informed, at least according to the rust server output.

**Comment by MrOwen** [comment]
I think it would be helpful to very clearly lay out the capabilities of notify_push in the readme. Obviously the scope of notify_push will grow as more applications adopt the sdk but right now, if you're a new user, you don't really know what notify_push is capable of. For now, it seems the current capabilities are:

* Send file notification events to desktop clients causing a refresh of file lists (not sure if this is correct terminology/phrasing). Mobile clients do not yet support this capability.
* Nextcloud push notifications for user-configured events (guest downloads a file, sharing options changed, etc.)
* Real-time file list updates from the Nextcloud web application (files app) are currently not supported

Not sure what the best phrasing to use for push notifications working in-browser but not file list updates. End-users probably assume those two are tied together but in this case, they are not.
