### ISSUE TITLE
notify_push does not autodetect database SSL settings from config.php

### ISSUE THREAD

**Issue by FleetAdmiralButter** [nextcloud/notify_push#117]
The notify_push service does not enable SSL connections to the database after following the instructions in https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html#ssl-for-mysql-database.

The service continues connecting to the database using a plaintext connection, causing errors if MySQL is started with --require_secure_transport=ON.

Starting the binary manually results in:
```
RUST_BACKTRACE=full /var/www/html/apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php
Error:
   0: Failed to connect to Nextcloud database
   1: error returned from database: 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.
```

DB options in Nextcloud config.php:
```
'dbhost' => '',
  'dbport' => '',
  'dbdriveroptions' =>
  array (
    1007 => '/mysql-tls-data/client-key.pem',
    1008 => '/mysql-tls-data/client-cert.pem',
    1009 => '/mysql-tls-data/ca.pem',
    1014 => false,
  ),

```

Output from notify_push's --dump-config (DB host, username, and pw were correct but are redacted here):
```
database: AnyConnectOptions(
        MySql(
            MySqlConnectOptions {
                host: "",
                port: ,
                socket: None,
                username: "",
                password: Some(
                    "",
                ),
                database: Some(
                    "",
                ),
                ssl_mode: Disabled,
                ssl_ca: None,
                statement_cache_capacity: 100,
                charset: "utf8mb4",
                collation: None,
                log_settings: LogSettings {
                    statements_level: Info,
                    slow_statements_level: Warn,
                    slow_statements_duration: 1s,
                },
            },
        ),
    ),
```

**Comment by icewind1991** [comment]
Hello, can you try with binary from https://github.com/nextcloud/notify_push/actions/runs/1094489980 and see if that fixes your issue

**Comment by FleetAdmiralButter** [comment]
Thanks @icewind1991.

I replaced the binary in the apps folder with the one you linked and ran into a different error:

```
RUST_BACKTRACE=full /var/www/html/apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php
Error:
   0: Failed to connect to Nextcloud database
   1: error occurred while attempting to establish a TLS connection: InvalidDNSNameError
   2: InvalidDNSNameError
```

--dump-config puts out:
```
Config {
    database: AnyConnectOptions(
        MySql(
            MySqlConnectOptions {
                host: "", 
                port: ,
                socket: None,
                username: "",
                password:,
                database: Some(
                    "nextcloud",
                ),
                ssl_mode: VerifyCa,
                ssl_ca: Some(
                    File(
                        "/mysql-tls-data/ca.pem",
                    ),
                ),
```

Looks like it is trying to establish a TLS connection at least. I checked the database connection information against config.php and it is being read correctly. It should be connecting to the database directly via a local IP, not sure why its running into problems with name resolution.

**Comment by icewind1991** [comment]
The push server does not support connecting to an ip directly using ssl due to an upstream limitation, you have to connect by hostname instead if you want to use ssl at the moment

**Comment by acsfer** [comment]
Related to https://github.com/nextcloud/notify_push/issues/79

**Comment by acsfer** [comment]
@icewind1991 is this a limitation (Wontfix) or a bug that will be fixed (upstream)?

**Comment by FleetAdmiralButter** [comment]
Thanks @icewind1991, I updated to version 0.2.2 and it works well with the database after adding an entry to /etc/hosts to point to it.
