### ISSUE TITLE
Not working for raspberry pi 4

### ISSUE THREAD

**Issue by toboga** [nextcloud/notify_push#12]
Tried to install on raspberry. Got error

"bundled binary not working on your system."

**Full error Message**

```
# sudo -u www-data php occ notify_push:setu
This setup wizard is intended for use on single server instances
where the nextcloud server, web server/reverse proxy and push daemon all run on the same machine.
If your setup is more complex or involves any kind of load balancing
you should follow the manual setup instruction on the README instead
https://github.com/nextcloud/notify_push
Press enter to continue or ESC to cancel...

🗴 bundled binary not working on your system.

```

**Comment by icewind1991** [comment]
Can you check if you're using version 0.1.1 and not 0.1.0, if you're using 0.1.0 you'll have to manually make the bundled binary executable.
The binary for your pi will be either in `notify_push/bin/aarch64` or `notify_push/bin/armv7` depending on if your os is 64bit (check with `uname -m`). which you'll have to make executable with

```
chmod +x notify_push/bin/<arch>/notify_push
```

if that doesn't solve it please try running `notify_push --version` manually

**Comment by SimplyCorbett** [comment]
I'm having the same issue on debian 10. I have 0.1.1 installed and have manually set the executable with chmod +x.

**Comment by PVince81** [comment]
with the [0.1.2 release](https://github.com/nextcloud/notify_push/releases/tag/v0.1.2) the aarch64 binary seems to start fine on Rpi OS on a Rpi4
`Linux rpi4.local 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux`

**Comment by toboga** [comment]
Thanks for your fast response and your fast fix. I will test it soon.

**Comment by SimplyCorbett** [comment]
0.1.2 fixes it, thanks!

**Comment by toboga** [comment]
Version 0.1.3 is out ;-). 

This fixed the error.
