### ISSUE TITLE
Systemd required for setup

### ISSUE THREAD

**Issue by pegasus87** [nextcloud/notify_push#120]
Hi,

I'm trying to setup notify_push but when running the occ setup it stops with following message:

```
sudo -u nginx ./occ notify_push:setup

This setup wizard is intended for use on single server instances
where the nextcloud server, web server/reverse proxy and push daemon all run on the same machine.
If your setup is more complex or involves any kind of load balancing
you should follow the manual setup instruction on the README instead
https://github.com/nextcloud/notify_push
Press enter to continue or ESC to cancel...

🗴 your system doesn't seem to be using systemd.
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push
```

There is no systemd on this server. notify_push ist handled by openrc init system without any problems. Why is systemd required to run the setup?

**Comment by icewind1991** [comment]
As the message says, follow the steps in the readme instead.

systemd is the init system supported by the setup wizard because it's the most common one

**Comment by pegasus87** [comment]
Thanks! That doesn't really answer the question why systemd is required but ok... as I said, the notify_push service is running without systemd as init system so it doesn't make any sense to exclude not-systemd users.
