### ISSUE TITLE
add support for directly listening on TLS encrypted port

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/notify_push#126]
Hi there,

it would be great if notify_push supported directly listening on a TLS encrypted port.

That way an additional reverse proxy in the middle could be omitted in setups where there already is a (loadbalancer-)proxy involved and running notify_push running on the same host as Nextcloud itself is not an option (e.g. because of a loadbalanced setup).

**Comment by icewind1991** [comment]
Fixed with 0.3.0
