### ISSUE TITLE
armv7 bin directory should be armv7l

### ISSUE THREAD

**Issue by PascalHeynmoeller** [nextcloud/notify_push#130]
Our NCPi script uses uname -m to resolve architecture
in my case this is armv7l but the bin dir of notify_push is ...armv7/
manual intervention or hardcoding is needed.

I kindly ask you to change the name of the architecture directory where the binary are found to armv7l?

details in:
https://github.com/nextcloud/nextcloudpi/issues/1326#issuecomment-917388467

**Comment by nachoparker** [comment]
thanks for your testing. I think this is fine, as there are different possible outputs for different armv7 flavors, this is something we can handle in NCP

**Comment by PascalHeynmoeller** [comment]
Ok I will close this issue. thank you.
