### ISSUE TITLE
[proxy:error] and [proxy_wstunnel:error]

### ISSUE THREAD

**Issue by platofan23** [nextcloud/notify_push#137]
Hello,

I use Nextcloud with the High-Performance-BackUP. This works great as it is described in the instructions.
But I always get the error (Apache2, php8.0, nextcloud 22.2.0.2):

> [Tue Nov 02 19:20:04.337573 2021] [proxy:error] [pid 14312:tid 3237745664] (111)Connection refused: AH00957: WS: attempt to connect to XXX:7867 (XXX) failed

> [Tue Nov 02 19:20:04.338471 2021] [proxy_wstunnel:error] [pid 14312:tid 3237745664] [client XXX:60456] AH02452: failed to make connection to backend: XXXX

My VHOST of nextcloud is:

<IfModule mod_ssl.c> </p>
<VirtualHost _default_:443>
        ServerAdmin XXX
        ServerName XXX
    DocumentRoot /var/www/nextcloud
    CustomLog /var/log/apache2/nc-access.log combined
    ErrorLog  /var/log/apache2/nc-error.log
    Include /etc/letsencrypt/options-ssl-apache.conf
    RequestHeader set X-Forwarded-Proto "https"
    <IfModule http2_module>
                Protocols h2 h2c http/1.1
                H2Direct on
                H2StreamMaxMemSize 5120000000
    </IfModule>
    SSLEngine on
    SSLProxyEngine on
        ProxyRequests Off
        ProxyErrorOverride Off
        ProxyPass /push/ws ws://XXX:7867/wss
        ProxyPass /push/ http://XXX::7867/
        ProxyPassReverse /push/ XXX:7867/
        ProxyPreserveHost On
        ProxyTimeout 600
    SSLProxyEngine off
    RewriteEngine on
        RewriteCond %{HTTP:UPGRADE} =websocket [NC]
        RewriteRule /push/wss/(.*) ws://XXX::7867/$1 [P,L]
        RewriteCond %{HTTP:UPGRADE} !=websocket [NC]
        RewriteRule /push/(.*) http://XXX::7867/$1 [P,L]
    <Directory /var/www/html/nextcloud>
        #Options -Indexes -Includes  +FollowSymlinks
                AllowOverride All
        <IfModule mod_dav.c>
                 Dav off
        </IfModule>
        <IfModule authz_core_module>
        Require all denied
        <RequireAny>
                Require ip 127.0.0.1
                Require ip ::1
                Require ip 10.6.0.0/24
                Require ip 192.168.2.0/24
        </RequireAny>
        </IfModule>
        SSLRenegBufferSize 10486000
        LimitRequestBody 0
        </Directory>
    SSLCertificateFile /etc/letsencrypt/live/XXX:/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/XXX:/privkey.pem
        <IfModule mod_headers.c>
        Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains"
        </IfModule>
</VirtualHost>
</IfModule>

So now how can i solve this error?

**Comment by DanScharon** [comment]
you seem to have a typo in this line:
>  ProxyPass /push/ws ws://XXX:7867/wss
this should be only one s at /ws

you could also have a look at this example: https://github.com/nextcloud/notify_push/issues/44#issuecomment-908463438
No need for mod_rewrite and the corresponding rewrite rules
