### ISSUE TITLE
Pre auth going wild

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notify_push#139]
In the coffee call just now something went wrong and from that onwards I received a pre_auth request every second:

![Bildschirmfoto von 2021-11-10 11-14-25](https://user-images.githubusercontent.com/213943/141094886-d3e1d6f1-c49b-45a6-82c5-4cdb8d58e3b5.png)

They are all good and return a token, but it seems to not use it but instead does another request?

**Comment by nickvergessen** [comment]
Same error happened to other people in the same call

**Comment by icewind1991** [comment]
is it trying to connect to the push server after doing the pre auth?

**Comment by nickvergessen** [comment]
That would be a websocket request? Not seeing anything apart from the XHR to pre_auth.

**Comment by nickvergessen** [comment]
Seems our service broke yesterday 14 UTC
```
cat /var/log/apache2/access.log.1 | grep pre_auth | egrep -o "2021:.." | sort | uniq -c
     52 2021:00
      4 2021:01
      2 2021:03
      2 2021:04
     19 2021:05
     19 2021:06
     86 2021:07
     99 2021:08
    118 2021:09
    114 2021:10
    172 2021:11
    169 2021:12
    165 2021:13
  26952 2021:14
  70525 2021:15
  67986 2021:16
  58904 2021:17
  63187 2021:18
  56021 2021:19
  49058 2021:20
  41592 2021:21
  34715 2021:22
  26332 2021:23
```

**Comment by icewind1991** [comment]
the js client does retry backoff now if it can't connect to ws after pre-auth
