### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by traxys** [nextcloud/notify_push#14]
The app just had a version bump, but the rust application did not, I just updated the Cargo.toml to say `0.1.1`, or else I would get an error from `occ notify_push:setup https://......./push` that the versionned mismatched

Maybe going forward you could mark point releases of the app as compatible with point releases of the rust program? Maybe the fix that I did was a bit dirty

**Comment by syntron** [comment]
I can confirm this - app and binary do not match; I'm not sure if I can recompile it; thus, I hope for an update ...

**Comment by icewind1991** [comment]
Fixed with 0.1.2
