### ISSUE TITLE
nginx error logs flooded

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/notify_push#144]
```
[error] 368292#368292: *611 connect() failed (111: Connection refused) while connecting to upstream, client: 109.43.49.225, server: server, request: "GET /push/ws HTTP/1.1", upstream: "http://127.0.0.1:7867/ws", host: "host"
[warn] 368292#368292: *611 upstream server temporarily disabled while connecting to upstream, client: 109.43.49.225, server: server, request: "GET /push/ws HTTP/1.1", upstream: "http://127.0.0.1:7867/ws", host: "host"
[error] 64795#64795: *26970 no live upstreams while connecting to upstream, client: 93.227.155.65, server: server, request: "GET /push/ws HTTP/1.1", upstream: "http://localhost/ws", host: "host"
```

**Comment by joshtrichards** [comment]
Any other context you can recall?

Unfortunately this is going to be challenging to diagnose without logs:

https://github.com/nextcloud/notify_push#logging

(In case it continues to this day or comes up again).

A wild guess is the push server coming online before Redis or DB services. That's pure speculation and many other possibilities exist.

**Comment by joshtrichards** [comment]
Closing since this is a couple years old and not actionable with the info on-hand at this point.  Can reopen if reoccurs.
