### ISSUE TITLE
0.3.0: No updated Docker tag/image

### ISSUE THREAD

**Issue by nRaecheR** [nextcloud/notify_push#145]
Version 0.3.0 has been released some days ago, there's still no image/tag for this version on Docker Hub. When will the "official" image be updated?
Thank you!

**Comment by major-mayer** [comment]
I would be interested too! It's been quite a while since November.

**Comment by ranomier** [comment]
Miau? :black_cat:

**Comment by nRaecheR** [comment]
With release of 0.4.0 of the notify_push server/app, the docker image was updated too...so we can close this issue now.
