### ISSUE TITLE
Password authentication failed with Redis local socket

### ISSUE THREAD

**Issue by mklemme1** [nextcloud/notify_push#15]
I learned from #10 that the message "Password authentication failed" is linked to Redis.
My Redis is configured like this

```
 'redis' =>  
  array ( 
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'dbindex' => 1,
    'password' => 'REMOVED',
  ), 
```

For a first test, I run the program directly from the command line
I then get the error message:

```
$ htdocs/apps/notify_push/bin/x86_64/notify_push  htdocs/config/config.php

Error: 
   0: Password authentication failed

Location:
   /tmp/krankerl.40zg80MPYiwS/notify_push/src/lib.rs:108

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                 ⋮ 1 frame hidden ⋮                               
   2: notify_push::main::{{closure}}::h68b9e89262183550
      at <unknown source file>:<unknown line>
   3: notify_push::main::h3ddb05ca74373b2a
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_begin_short_backtrace::h1bae9b7ed3e6fe5e
      at <unknown source file>:<unknown line>
   5: main<unknown>
      at <unknown source file>:<unknown line>
```

Is this linked to using Redis with a local socket?

I am getting here because the configuration via occ failed in the first place

```
$ php htdocs/occ  notify_push:setup
The current PHP memory limit is below the recommended value of 512MB.
This setup wizard is intended for use on single server instances
where the nextcloud server, web server/reverse proxy and push daemon all run on the same machine.
If your setup is more complex or involves any kind of load balancing
you should follow the manual setup instruction on the README instead
https://github.com/nextcloud/notify_push
Press enter to continue or ESC to cancel...

🗴 bundled binary not working on your system.
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push
hessen-server@adfc-hessen-server:~/cloud/test$ 
```

This is Ubuntu 18.04 LTS, Client Push version 0.1.1 downloaded from the Nextcloud App store.
Nextcloud and Redis are installed on the same server.

Thanks
  M

**Comment by icewind1991** [comment]
can you run the binary with `LOG=notify_push=trace` set as environment variable, which will cause it to print the parsed config on start. And see if the redis config is as expected

**Comment by s644** [comment]
Hi,
I've just setup HPB with local radis socket and password protection. But I configured everything as described in the manual setup section, because Radis isn't detected if you run NC in a jail environment. I struggeled with authentification, too, but it was because i forgot to add propper socket permission as described here:

https://docs.nextcloud.com/server/21/admin_manual/configuration_server/caching_configuration.html

`usermod -a -G redis www-data
`

**Comment by mklemme1** [comment]
running it again with `LOG=notify_push=trace`:

```
 htdocs/apps/notify_push/bin/x86_64/notify_push  htdocs/config/config.php
[2021-02-22 21:25:36.357628 +01:00] TRACE [notify_push] src/main.rs:41: Running with config: Config { database: AnyConnectOptions(MySql(MySqlConnectOptions { host: "localhost", port: 3306, socket: Some("/var/run/mysqld/mysqld.sock"), username: "CORRECT", password: Some("CORRECT"), database: Some("CORRECT"), ssl_mode: Preferred, 
ssl_ca: None, statement_cache_capacity: 100, charset: "utf8mb4", collation: None, log_settings: LogSettings { statements_level: Info, slow_statements_level: Warn, slow_statements_duration: 1s } })), 
database_prefix: "oc_", redis: ConnectionInfo { addr: Unix("/var/run/redis/redis-server.sock"), db: 1, username: None, passwd: Some("CORRECT") }, nextcloud_url: "CORRECT" }
[2021-02-22 21:25:36.358653 +01:00] DEBUG [notify_push::storage_mapping] src/storage_mapping.rs:96: querying storage mapping for 1
Error: 
   0: Password authentication failed

Location:
   /tmp/krankerl.40zg80MPYiwS/notify_push/src/lib.rs:108

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::hfa9a61744f0682a9
      at <unknown source file>:<unknown line>
   2: notify_push::main::{{closure}}::h68b9e89262183550
      at <unknown source file>:<unknown line>
   3: notify_push::main::h3ddb05ca74373b2a
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_begin_short_backtrace::h1bae9b7ed3e6fe5e
      at <unknown source file>:<unknown line>
   5: main<unknown>
      at <unknown source file>:<unknown line>

```

I have checked the confidential items and replaced them with the word `CORRECT`.

**Comment by mklemme1** [comment]
Hallo s644
> Hi,
> I've just setup HPB with local radis socket and password protection. But I configured everything as described in the manual setup section, because Radis isn't detected if you run NC in a jail environment. I struggeled with authentification, too, but it was because i forgot to add propper socket permission as described here:
> 
> https://docs.nextcloud.com/server/21/admin_manual/configuration_server/caching_configuration.html

Thanks for pointing that out.
The user running both the PHP process and `notify_push` is in a group having write access to the Redis socket.

**Comment by mklemme1** [comment]
Okay, it was on my side:
The Redis configuration had lost its password.
Apparently Nextcloud/PHP could still connect.
