### ISSUE TITLE
Conflicts with Group Folders

### ISSUE THREAD

**Issue by MiningPickaxe** [nextcloud/notify_push#152]
Hello,

this App conflicts with Group Folders, when configuring it you receive the following error: `Cannot use OCP\Constants as Constants because the name is already in use at /var/www/nextcloud/apps/groupfolders/lib/Command/ACL.php#35 `

**Comment by kleener** [comment]
I guess you mean the problem: https://github.com/nextcloud/groupfolders/issues/1854
That might have been solved yesterday.
