### ISSUE TITLE
self-test fails

### ISSUE THREAD

**Issue by aakerbeere** [nextcloud/notify_push#161]
I'm trying to set up "notify push".
Feeling to be pretty close but the self-test actually get
```
Push binary seems to be running already
✓ push server seems to be functioning correctly.
Reverse proxy seems to be configured already
🗴 failed to run self-test.
test output: ✓ redis is configured
             ✓ push server is receiving redis messages
             ✓ push server can load mount info from database
             ✓ push server can connect to the Nextcloud server
             ✓ push server is a trusted proxy
             🗴 failed to get binary version: Client error: `POST https://sld.tld/push/test/version` resulted in a `405 Method Not Allowed` response:
             HTTP method not allowed
```
Apache2 is running NC on a subdomain such as `https://sub.sld.tld` and i have set the service "notify_push" to `Environment=NEXTCLOUD_URL=https://sub.sld.tld`

Any hint or guidance to resolve this would be very welcome.

thx

**Comment by mritzmann** [comment]
`HTTP method not allowed` sounds like a problem with the reverse proxy (Apache).

**Comment by aakerbeere** [comment]
thx @mritzmann 

I followed the [instructions](https://github.com/nextcloud/notify_push/blob/main/README.md#apache) to set up the reverse proxy.

**Comment by iamkhalidbashir** [comment]
suddently starting this issue with nextcloud/all-in-one:latest

**Comment by joshtrichards** [comment]
@aakerbeere This would arise from your broader reverse proxy / SSL server configuration most likely. Can you check your Apache error log? And also maybe double-check your Apache configuration in general.

**Comment by aakerbeere** [comment]
Sorry @joshtrichards. Thx for commenting. What you are talking about is probably what i have done after the error came up.

I forgot about this since it's a long time i didn't got answered before.
It's actually working as expected. No more issues:
```
systemd[1]: Started notify_push.service - Push daemon for Nextcloud clients.
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
✓ push server is running the same version as the app
```
I apologize.

Going to close as solved with this comment.
