### ISSUE TITLE
Add Support for nextcloud 24

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/notify_push#164]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by nursoda** [comment]
I tested notify_push 0.3 in my Arch Linux server setup (PHP8.1, NGINX/PHP-FPM, MariaDB) with NC24b2, b3 and RC1 – no issues, so a simple version bump should do. Created [PR167](https://github.com/nextcloud/notify_push/pull/167) to achieve this.

**Comment by cscholz** [comment]
> I tested notify_push 0.3 in my Arch Linux server setup (PHP8.1, NGINX/PHP-FPM, MariaDB) with NC24b2, b3 and RC1 – no issues, so a simple version bump should do. Created [PR167](https://github.com/nextcloud/notify_push/pull/167) to achieve this.

Can I confirm on Debian OS

**Comment by nursoda** [comment]
Got 0.4.0 – thanks a lot! 👍🏻

**Comment by cscholz** [comment]
> Got 0.4.0 – thanks a lot! 👍🏻

I join in the thanks
