### ISSUE TITLE
postgresql without password does not work

### ISSUE THREAD

**Issue by tomhub** [nextcloud/notify_push#188]
Hi

I migrated nextcloud database from mariadb to postgresql, and now I noticed that notify_push cannot connect to postgres:
```
notify_push[3164]:     Caused by: invalid database configuration: no password set
notify_push[3164]:     Caused by: no password set
```
nextcloud works fine though.

**Comment by icewind1991** [comment]
Please check if the following build solves the problem: [notify_push.tar.gz](https://github.com/nextcloud/notify_push/files/11110969/notify_push.tar.gz)

**Comment by tomhub** [comment]
Seems to running without db password - log is clear
