### ISSUE TITLE
error trying to connect

### ISSUE THREAD

**Issue by ManySolutions** [nextcloud/notify_push#196]
When i run the OCC notify_push:setup command I get runthrough to the error:
src/main self test failed: error while communicating with the nextcloud instance
 src/lib.rs:287: Error while trying to get cookie from Nextcloud error sending request for url (http://localhost/index.php/apps/notify_push/test/cookie): error trying to connect: tcp connect error: Connection refused (os error 111)

in the nextcloud log i get the error:
[PHP] Error: Error: rewind(): Stream does not support seeking at /var/www/vhosts/cloud..co.uk/httpdocs/apps/notify_push/lib/SetupWizard.php#153 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError()
1. /var/www/vhosts/cloud..co.uk/httpdocs/apps/notify_push/lib/SetupWizard.php line 153
   rewind()
2. /var/www/vhosts/cloud..co.uk/httpdocs/apps/notify_push/lib/Command/Setup.php line 149
   OCA\NotifyPush\SetupWizard->testAutoConfig()
3. /var/www/vhosts/cloud..co.uk/httpdocs/3rdparty/symfony/console/Command/Command.php line 255
   OCA\NotifyPush\Command\Setup->execute()
4. /var/www/vhosts/cloud..co.uk/httpdocs/3rdparty/symfony/console/Application.php line 1009
   Symfony\Component\Console\Command\Command->run()
5. /var/www/vhosts/cloud..co.uk/httpdocs/3rdparty/symfony/console/Application.php line 273
   Symfony\Component\Console\Application->doRunCommand()
6. /var/www/vhosts/cloud..co.uk/httpdocs/3rdparty/symfony/console/Application.php line 149
   Symfony\Component\Console\Application->doRun()
7. /var/www/vhosts/cloud..co.uk/httpdocs/lib/private/Console/Application.php line 213
   Symfony\Component\Console\Application->run()
8. /var/www/vhosts/cloud..co.uk/httpdocs/console.php line 100
   OC\Console\Application->run()
9. /var/www/vhosts/cloud..co.uk/httpdocs/occ line 11
   require_once("/var/www/vhosts ... p")

at 2022-11-16T16:21:14+00:00

And nothing in the apache logs.

**Comment by koelle25** [comment]
Can you elaborate on your setup? Do the Nextcloud/Apache and the Notify-Push service run on the same machine? Are you using (docker) containers?

**Comment by joshtrichards** [comment]
Closing this out due to no response from the original reporter after 8 months.
