### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by timscha** [nextcloud/notify_push#21]
When installed via the appstore of Nextcloud the ./apps/notify_push/bin/x86_64/notify_push has the wrong permissions.
I had to manually set them to 755. Without this permissions the service isn't able to start the daemon. So it should be at least in the readme to correct the permissions.

Tested on Debian 10.

Then systemctl gives the error:

notify_push.service: Failed to execute command: Permission denied

**Comment by raimund-schluessler** [comment]
Related to https://github.com/nextcloud/notify_push/issues/9.

**Comment by icewind1991** [comment]
Can you check if 0.1.3 fixes this for you?

**Comment by timscha** [comment]
Jupp @icewind1991, it's fine again. Thanks!
