### ISSUE TITLE
Document log levels

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/notify_push#227]
Log levels are not documented.

It would be great to have a table in the documentation their value and meaning.

**Comment by arnowelzel** [comment]
The log levels are documented in the README file. What do you miss here? I'd expect the usual behaviour here:

`error` - Errors 
`warn` - Errors, warnings 
`info` - Errors, warnings, informational messages 
`trace` - Errors, warnings, informational messages and trace messages

You can see this as a level of how detailed the log is. When you set it to `error` this means **only** error messages will be logged. When set to `warn` you will see error messages and also warnings. And the most detailed level is `trace` where you see all messages possible, even those which just inform you about internal procedures going on.

----

### Logging

By default, the push server only logs warnings, you can temporarily change the log level with an occ command

```bash
occ notify_push:log <level>
```

Where level is `error`, `warn`, `info`, `debug` or `trace`, or restore the log level to the previous value using

```bash
occ notify_push:log --restore
```

Alternatively you can set the log level of the push server in the `LOG` environment variable.

**Comment by nursoda** [comment]
IMHO that's sufficient. If OP and/or maintainer agrees, this issue should be closed.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/notify_push#logging

Yeah, let's close this issue out. :)
