### ISSUE TITLE
Since about 10 days every day push alert for the same thing - how to delete?

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/notify_push#230]
Hello, i made a test if push notifications work and set it for download a shared folder - and now since about 10 days on every start of my laptops (4 different) comes that alert from the Desktop Client - but i had de-selected the option after the test for about 10 days. 

How can i delete the push notifications that the desktop clients don't make this old alert?

I use Linux Mint 21 and the current Nextcloud version 3.7.3 - and the Nextcloud version on the Server ist 25.0.2

**Comment by arnowelzel** [comment]
The Nextcloud database has a table `oc_notifications`. Maybe you find the notification there and can just delete it. Just make sure you have a backup of your database before you try to modify the database.

For database editing I recommend [DBeaver](https://dbeaver.io) which also supports using an SSH tunnel to the server.

**Comment by stefan-franz** [comment]
Thanks for your answer. I found a solution: I logged in to my nextcloud and quit the message in the browser. Seems that the Desktop Clients not transmit the quit of notifications.

**Comment by arnowelzel** [comment]
Well - I don't think that this is related to notify_push at all since notifications are also sent without notify_push installed. notify_push will only make sure, that file changes will also be pushed as notifications so clients don't have to poll regularly for that.
