### ISSUE TITLE
Feature request: Listen on unix socket instead of tcp port

### ISSUE THREAD

**Issue by nextcloud486153** [nextcloud/notify_push#24]
I think that it would be useful to have the option to listen on a unix socket instead of on a tcp port, with the path being configurable via argument or environment variable.

**Comment by membero** [comment]
I have created a PR for this: https://github.com/nextcloud/notify_push/pull/39

**Comment by icewind1991** [comment]
Fixed in 0.1.5

**Comment by GoSpursGoNL** [comment]
Looks like a useful improvement. Will the [documentation](https://github.com/nextcloud/notify_push/blob/main/README.md) be updated? It is not fully clear to me what I should change to the service and/or Apache configuration. Thank you!

**Comment by nextcloud486153** [comment]
@GoSpursGoNL the service describes the environment and arguments used. Right now it configures it via an environment variable:
```
Environment = PORT=7867 # Change if you already have something running on this port
```
You can replace the `PORT` variable:
```
Environment = SOCKET_PATH=/tmp/push.sock
```

Then you should edit your webserver configuration. Instead of the localhost url (`http://localhost:7867/`) you have to use the appropriate URL for unix sockets.
* Apache: `unix:/tmp/push.sock|http://localhost/` (the second part is the hostname to use, not where to connect)
* Nginx: `http://unix:/tmp/push.sock`

Obviously, if you set a different `SOCKET_PATH`, you need to replace `/tmp/push.sock` in the examples above.
