### ISSUE TITLE
Notify_push without init system available

### ISSUE THREAD

**Issue by merzak274j** [nextcloud/notify_push#249]
I would like to use the files HPB but unfortunately my hosting provider does not allow me to create a daemon.

I’m wondering if it’s possible to use a cron that checks if the push server is running and if it’s not restarts it ? It may not be as reliable as using an init system but it’s maybe the only way I can be able to run the push server on the same host as my nextcloud instance. 

It seems like this would be much simpler than setting up a reverse proxy to a different machine on a different network.

My provider does provide me with redis, so it seems all I am missing is a daemon.

After a discussion with chatGPT I was thinking something like could work ?

```
#!/bin/bash

# Set environment variables
export SOCKET_PATH=/path/to/socket/nextcloud.socket

# Check if push server is running
if ! pgrep -x "notify_push" > /dev/null
then
    # Start the push server
    nohup /path/to/push/binary/notify_push --config=/path/to/nextcloud/config/config.php --socket-path=$SOCKET_PATH &
fi

```

Since I’m not a developer, I thought to validate my approach with the community before trying it. Any response would be much appreciated

**Comment by GieltjE** [comment]
I'd maybe add a sleep to the loop, but otherwise it looks fine.
Just remember to restart the daemon after upgrading the plugin.

**Comment by nursoda** [comment]
@merzak274j Did you test your script? Does it work well over time?
If so, this should be included in the documentation (README), so you may provide a PR.

**Comment by merzak274j** [comment]
So far I have not had any luck.

I can start the push server and I believe it’s running because I see a process ID when I run pgrep -x "notify_push" 

However when getting to the occ notify_push:setup step, it doesn’t see the push server and says it’s not running. Self-check fails as well.

I’ve tried pointing the setup to localhost or 127.0.0.1 but this hasn’t worked. 

Maybe if notify push setup does not see that the service exists, or is running, instead of checking if the server is running, then it fails and at that point it’s necessary to use a URL as an argument, at which point a reverse proxy is needed.

I’m not familiar enough with fundamentals to understand why my setup isn’t working.

**Comment by icewind1991** [comment]
If you're on a shared host with no option to open a port or configure the reverse proxy there is no way to get things working.

**Comment by merzak274j** [comment]
> If you're on a shared host with no option to open a port or configure the reverse proxy there is no way to get things working.

OK, thank you for the reply
