### ISSUE TITLE
name mismatch and install failure

### ISSUE THREAD

**Issue by noci2012** [nextcloud/notify_push#25]
notify_push is named client_push in the app store...
This affects probably documentation, etc. as ell as the README.md

Then following the instruction on installing client_push:
run occ notify_push:setup results in:

```
This setup wizard is intended for use on single server instances
where the nextcloud server, web server/reverse proxy and push daemon all run on the same machine.
If your setup is more complex or involves any kind of load balancing
you should follow the manual setup instruction on the README instead
https://github.com/nextcloud/notify_push
Press enter to continue or ESC to cancel...

🗴 failed to run self-test with auto-generated config.
test output: 
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push
```

Which says: in Quick setup
```
The app comes with a setup wizard that should guide you through the setup process for most setups.

Install the notify_push app from the appstore
Run occ notify_push:setup and follow the provided instructions
```
Which fails... see above.

Setup notify_push service only describes the systemd setup. A setup for non-systemd would be nice as well.

**Comment by noci2012** [comment]
For correctly setting up proxy stuff in nginx also check out: http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by icewind1991** [comment]
I've updated the documentation to reflect the name the app has in the appstore.

Have you tried following the manual setup steps? For non systemd-setups you will need to configure your init system of choice to run the binary with the correct parameters and env variables, I currently can't provide concrete instructions for that though.

**Comment by noci2012** [comment]
Yes, I tried manual install and it wasn't a walk in the park either.

The only way to setup the proxy is using the realip module setup in nginx.
Without valid settings the netcloud_push module will continue to complain about an invalid proxy.
