### ISSUE TITLE
Lots of 'Using ${var} in strings is deprecated' errors on NC26 using PHP 8.2

### ISSUE THREAD

**Issue by nursoda** [nextcloud/notify_push#257]
I see many of those:
`Using ${var} in strings is deprecated, use {$var} instead at /…/apps/notify_push/lib/SetupWizard.php#247`
Can anyone confirm that this is not my installation only?

**Comment by solracsf** [comment]
Should be fixed by https://github.com/nextcloud/notify_push/issues/257
Nothing to worry about.
