### ISSUE TITLE
Docker Hub images not being updated

### ISSUE THREAD

**Issue by mkiah** [nextcloud/notify_push#264]
The newest tagged version is 0.6.1 on docker hub, and the 0.6.2 release is missing. I wonder if it's related to having changed the namespace of the notify_push repo from icewind1991 to nextcloud?

![image](https://user-images.githubusercontent.com/46502806/233798671-22af2aed-a18a-471b-9175-71691cbdab56.png)

**Comment by joshtrichards** [comment]
It was updated to v0.6.3 on Docker Hub on May 16, 2023 so I think this issue can be closed out.

**Comment by thomas-mc-work** [comment]
This has happened again: repo is on `0.6.5` vs docker hub on version `0.6.3`. Isn't the publishing process automated?

**Comment by outermedia-cbo** [comment]
Should be re-opened: 

Most recent version on [hub.docker.com](https://hub.docker.com/r/icewind1991/notify_push/tags) is `0.6.11`. But `0.7.0` was released this Jul 29.

**Comment by thomas-mc-work** [comment]
I've ended up using the nextclod image as a working image for that purpose:

    services:
      nextcloud:
        …
      push:                                                                                                                               
        image: nextcloud:latest
        entrypoint: /usr/local/bin/notify_push /config.php
        volumes:                                                                                                                          
          - ./html/apps/notify_push/bin/x86_64/notify_push:/usr/local/bin/notify_push:ro
          - ./html/config/config.php:/config.php:ro
