### ISSUE TITLE
failed to detect app version app

### ISSUE THREAD

**Issue by syntron** [nextcloud/notify_push#27]
Could this error be due to different names? (notify_push <=> client_push); See also #25 

Any hint welcome!

= 1: run via occ =

sudo -u wwwrun /usr/bin/php -f /path/to/nextcloud/occ notify_push:setup
This setup wizard is intended for use on single server instances
where the nextcloud server, web server/reverse proxy and push daemon all run on the same machine.
If your setup is more complex or involves any kind of load balancing
you should follow the manual setup instruction on the README instead
https://github.com/nextcloud/notify_push
Press enter to continue or ESC to cancel...

🗴 failed to run self-test with auto-generated config.
test output: [2021-02-23 19:01:01.881358 +01:00] WARN [notify_push] src/lib.rs:131: failed to detect app version app: Response was of incompatible type: "Response type not string compatible." (response was nil)
             [2021-02-23 19:01:01.931068 +01:00] INFO [notify_push] src/main.rs:89: shutdown signal received, shutting down
             ✓ redis is configured
             🗴 using unencrypted https for push server is strongly discouraged
             🗴 push server url is set to localhost, the push server will not be reachable from other machines
             ✓ push server is receiving redis messages
             ✓ push server can load mount info from database
             🗴 push server can't connect to the Nextcloud server
             
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push

= 2: run directly =

./notify_push /path/to/nextcloud/config/config.php 
[2021-02-23 18:52:39.519612 +01:00] WARN [notify_push] src/lib.rs:131: failed to detect app version app: Response was of incompatible type: "Response type not string compatible." (response was nil)
The application panicked (crashed).
Message:  error binding to 0.0.0.0:80: error creating server listener: Address in use (os error 98)
Location: /home/robin/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.0/src/server.rs:283

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by icewind1991** [comment]
> 🗴 push server can't connect to the Nextcloud server

is the relevant error here, what is the `overwrite.cli.url` in your `config.php`?

**Comment by syntron** [comment]
> > 🗴 push server can't connect to the Nextcloud server
> 
> is the relevant error here, what is the `overwrite.cli.url` in your `config.php`?

It is pointing to the URL where the nextcloud instance can be reached:
  'overwrite.cli.url' => 'https://home.mattsys.de/-/cloud-dev',

**Comment by TheGreatestJannet** [comment]
I have the same issue: the only error message I have is `[2021-02-24 21:04:27.368389 +00:00] WARN [notify_push] src/lib.rs:131: failed to detect app version app: Response was of incompatible type: "Response type not string compatible." (response was nil)`

**Comment by TheGreatestJannet** [comment]
Despite this error I have got it to work! I was using docker I didn't map port 7867 to the host!

**Comment by icewind1991** [comment]
0.1.5 should give better diagnostics for this case

**Comment by syntron** [comment]
Using 0.1.5 I get some more messages; it seems to indicate that some action is possible via the reverse proxy. However, it is still not working.

(1) running it without any manually started binary (notify_push:setup)

🗴 failed to run self-test with auto-generated config.
test output: [2021-02-26 19:11:24.707958 +01:00] WARN [notify_push] src/lib.rs:241: Error while trying to get cookie from Nextcloud Response from nextcloud is not a number: invalid digit found in string
             [2021-02-26 19:11:24.709082 +01:00] INFO [notify_push] src/main.rs:78: shutdown signal received, shutting down
             ✓ redis is configured
             🗴 using unencrypted https for push server is strongly discouraged
             🗴 push server url is set to localhost, the push server will not be reachable from other machines
             ✓ push server is receiving redis messages
             ✓ push server can load mount info from database
             🗴 push server can't connect to the Nextcloud server
               Response from nextcloud is not a number: invalid digit found in string
             
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push

(2) running it with manually started binary (notify_push:setup)

Push binary seems to be running already
🗴 failed to run self-test.
test output: ✓ redis is configured
             🗴 using unencrypted https for push server is strongly discouraged
             🗴 push server url is set to localhost, the push server will not be reachable from other machines
             ✓ push server is receiving redis messages
             ✓ push server can load mount info from database
             🗴 push server can't connect to the Nextcloud server
               Response from nextcloud is not a number: invalid digit found in string
             
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push

messages from the binary:

[2021-02-26 19:08:55.516461 +01:00] DEBUG [notify_push] src/lib.rs:228: current test cookie is 641714933
[2021-02-26 19:08:55.521876 +01:00] DEBUG [notify_push] src/lib.rs:360: Received test cookie 848588801
[2021-02-26 19:08:55.526408 +01:00] DEBUG [notify_push] src/lib.rs:228: current test cookie is 848588801
[2021-02-26 19:08:55.529558 +01:00] DEBUG [notify_push] src/lib.rs:258: storage mapping count for 2 = 1
[2021-02-26 19:08:55.561185 +01:00] WARN [notify_push] src/lib.rs:241: Error while trying to get cookie from Nextcloud Response from nextcloud is not a number: invalid digit found in string

**Comment by syntron** [comment]
I got it working!

The important hint was found here: https://help.nextcloud.com/t/high-performance-backend-cannot-be-installed/109473/6

In the nextcloud config file the path has to end with a slash '/' - I did it for both - overwrite.cli.url and htaccess.RewriteBase - and it is working now.

Perhaps this can be checked by the tool or added to the manual?

**Comment by syntron** [comment]
Now the setup says it is up and running - but how can I test it? Is there any possibility to check if it is working?

**Comment by icewind1991** [comment]
Fixed with 400b3b0
