### ISSUE TITLE
Issue with storage mapping from database

### ISSUE THREAD

**Issue by berkaycagir** [nextcloud/notify_push#29]
Hey,

I'm getting the following output:

```
sudo -u www-data env LOG=notify_push=trace PORT=7867 RUST_BACKTRACE=1 /var/www/nextcloud/apps/notify_push/bin/x86_64/notify_push /var/www/nextcloud/config/config.php
[2021-02-23 22:06:23.597455 +01:00] TRACE [notify_push] src/main.rs:41: Running with config: Config { database: AnyConnectOptions(MySql(MySqlConnectOptions { host: "localhost", port: 5432, socket: None, username: "nextcloud", password: Some("redacted"), database: Some("nextcloud"), ssl_mode: Preferred, ssl_ca: None, statement_cache_capacity: 100, charset: "utf8mb4", collation: None, log_settings: LogSettings { statements_level: Info, slow_statements_level: Warn, slow_statements_duration: 1s } })), database_prefix: "oc_", redis: ConnectionInfo { addr: Tcp("localhost", 6379), db: 0, username: None, passwd: Some("redacted") }, nextcloud_url: "redacted" }
[2021-02-23 22:06:23.598362 +01:00] DEBUG [notify_push::storage_mapping] src/storage_mapping.rs:96: querying storage mapping for 1
Error: 
   0: Failed to test database access
   1: Failed to load storage mapping from database
   2: pool timed out while waiting for an open connection

Location:
   /tmp/krankerl.6wDVzxnHMC1t/notify_push/src/storage_mapping.rs:108

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                 ⋮ 1 frame hidden ⋮                               
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h37400b9659074ff9
      at <unknown source file>:<unknown line>
   3: notify_push::main::{{closure}}::h8353892e3b19db59
      at <unknown source file>:<unknown line>
   4: notify_push::main::h4f6958ef3c78b4fd
      at <unknown source file>:<unknown line>
   5: std::sys_common::backtrace::__rust_begin_short_backtrace::h35bee24ae9e94d86
      at <unknown source file>:<unknown line>
   6: main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```
Why could this be happening? I've done the same query myself and there's not a storage with ID 1.

Thanks.

**Comment by berkaycagir** [comment]
I think it could be about this line:

https://github.com/nextcloud/notify_push/blob/db56346de22867d7180d581cdb17159459885232/src/lib.rs#L105

Why the self_test function automatically queries for the storage ID 1?

**Comment by icewind1991** [comment]
It's failing to connect to the database, probably because of the use of `localhost` in the database config, which causes php to use the local unix socket instead of a local tcp connection.
There is *some* handling for this, but it doesn't handle all cases yet (such as apparently yours).

Can you check if either of the following files exists: `/tmp/mysql.sock` or `/var/run/mysqld/mysqld.sock`.
If neither of those exists you should be able to get the socket address from the `show variables like 'socket';` sql query.

**Comment by berkaycagir** [comment]
It's solved. My NC config file was like this:

```
'dbhost' => 'localhost:5432',
'dbport' => '',
```
I tried changing it to:

```
'dbhost' => 'localhost',
'dbport' => '5432',
```

Now it works without any problems.

The trace for reference after the change:
`[2021-02-24 17:19:11.731895 +01:00] TRACE [notify_push] src/main.rs:41: Running with config: Config { database: AnyConnectOptions(MySql(MySqlConnectOptions { host: "localhost", port: 3306, socket: Some("/var/run/mysqld/mysqld.sock"), username: "nextcloud", password: Some("redacted"), database: Some("nextcloud"), ssl_mode: Preferred, ssl_ca: None, statement_cache_capacity: 100, charset: "utf8mb4", collation: None, log_settings: LogSettings { statements_level: Info, slow_statements_level: Warn, slow_statements_duration: 1s } })), database_prefix: "oc_", redis: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, username: None, passwd: Some("redacted") }, nextcloud_url: "redacted" }`

**Comment by icewind1991** [comment]
Strange, according to my testing both of those cases should be handled the same

**Comment by berkaycagir** [comment]
That's weird. I also changed the redis address from `localhost` to `127.0.0.1` but didn't mention it as I thought it wasn't related. Could this've had an effect?

**Comment by icewind1991** [comment]
That could be the cause if `localhost` resolves to ipv6 but redis is only listening on ipv4.

With 0.1.4 it will always use ipv4 for `localhost` with redis
