### ISSUE TITLE
Can't upgrade apps - TypeError: OC_App::checkAppDependencies(): Argument #3 ($info) must be of type array, null given

### ISSUE THREAD

**Issue by chrisaga** [nextcloud/notify_push#332]
I cannot upgrade apps in NC 27.0.2.

`occ app:update --all` fails with
```
An unhandled exception has been thrown:
TypeError: OC_App::checkAppDependencies(): Argument #3 ($info) must be of type array, null given, called in /srv/data/web/vhosts/XXX/htdocs/lib/private/legacy/OC_App.php on line 834 and defined in /srv/data/web/vhosts/XXX/htdocs/lib/private/legacy/OC_App.php:1031
```

Same thing happens if I provide the name of an app to be updated instead of `--all`

Apparently it's not a 100% new issue since I've found some evidence for NC 24 (#151) and NC 26 [https://help.nextcloud.com/t/nc-26-0-4-2-typeerror-oc-app-checkappdependencies-argument-3-info-must-be-of-type-array-null-given/166889](https://help.nextcloud.com/t/nc-26-0-4-2-typeerror-oc-app-checkappdependencies-argument-3-info-must-be-of-type-array-null-given/166889).

The workaround I found is to immediately run the `occ app:update <app-name>` again **without doing anything else** (otherwise you have to clean manually the mess and reinstall the app).

**Comment by icewind1991** [comment]
I don't understand how this is related to this app?

Please open an issue in the server repo

**Comment by chrisaga** [comment]
You are right. I opened at the wrong place. Sorry
