### ISSUE TITLE
Assert while building in Gentoo

### ISSUE THREAD

**Issue by admorgan** [nextcloud/notify_push#344]
notify_push 0.6.3
rust 1.71.1
Gentoo Linux

When installing via the package manager I am getting an assert by the compiler, specifically 

```
rustc: /var/tmp/portage/dev-lang/rust-1.71.1/work/rustc-1.71.1-src/src/llvm-project/llvm/lib/Analysis/InstructionPrecedenceTracking.cpp:97: void llvm::InstructionPrecedenceTracking::validate(const llvm::BasicBlock*) const: Assertion `It->second == nullptr && "Block is marked as having special instructions but in fact it  has " "none!"' failed.
error: could not compile `notify_push` (bin "notify_push")
```

I have attached the full [build.log](https://github.com/nextcloud/notify_push/files/12823930/build.log)

**Comment by podkilla** [comment]
the problem still exists with version 0.6.6

**Comment by admorgan** [comment]
https://bugs.gentoo.org/910267 has found that the issue is Rust 1.17.1, as soon as one of the newer version is stable it should sort itself out.
