### ISSUE TITLE
Notification Timeout

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/notify_push#36]
Tried to share a file with a user who don't accept shares by default. 
Sharing doesn't work because of timeout. 
Got this line in the logfile:

GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications

**Comment by icewind1991** [comment]
That looks to be an error related to mobile push, not this app
