### ISSUE TITLE
Docker builds missing

### ISSUE THREAD

**Issue by mhzawadi** [nextcloud/notify_push#362]
Hello 👋🏼 

When did the to docker build stop, as I have not seen a 0.6.5 tag yet (https://hub.docker.com/r/icewind1991/notify_push)
Could they be restarted as part of the release process please?

**Comment by mhzawadi** [comment]
Hello 👋🏼 

Could a docker image be build now please?

**Comment by trajano** [comment]
@mhzawadi what's the official docker image for this one?

**Comment by mhzawadi** [comment]
@trajano I stopped building my image as the process got out of hand, switched to `miles170/notify_push`
