### ISSUE TITLE
Does the systemd unit need a restart after app update?

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/notify_push#37]
The binary `notify_push` is part of the app and is updated via NC's app store.
Does the `notify_push.service` need a restart when the app got updated? Or is this done during the update of the app?

**Comment by icewind1991** [comment]
Yes, the systemd service should be restarted after an upgrade.

I'll look into adding some sort of reminder for admins when the service needs a restart

**Comment by DecaTec** [comment]
Thanks for the clarification.
Maybe a paragraph in the readme about updating the app is a good idea?
