### ISSUE TITLE
How to set up notify_push assuming a docker installation of Nextcloud AIO?

### ISSUE THREAD

**Issue by dermot-mcg** [nextcloud/notify_push#375]
I get the following error in browser console: `WebSocket connection to 'wss://nextcloud.mydomain.com/push/ws' failed:`

The nginx is configured to catch push:

```
    location ^~ /push/ {
        proxy_pass http://localhost:7867$request_uri;
```

The service is up and running - using `docker ps` I see:
```
8b549a8333de   nextcloud/aio-notify-push:latest   "/start.sh"              6 days ago       Up 6 days (healthy)                                                                                                              nextcloud-aio-notify-push
```
Though its not listening on a port.

I run `sudo docker exec -ti --user www-data nextcloud-aio-nextcloud /var/www/html/occ notify_push:setup` and get this error:

```
🗴 your system doesn't seem to be using systemd.
  You can still use the app without systemd by following the manual setup instructions.
  See the steps in the README for manual setup instructions: https://github.com/nextcloud/notify_push
```

When I follow manual setup I see in the `/etc/systemd/system/notify_push.service` content:

```
ExecStart = /path/to/push/binary/notify_push /path/to/nextcloud/config/config.php
```

How can I refer to those paths if they are all different docker instances?

**Comment by joshtrichards** [comment]
If you're using AIO none of the above should be necessary. 

You mentioned you have Nginx apparently in front of AIO. 

Your Nginx RP config should be very simple:

https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx

All of the details are handled behind the scenes in AIO's web server/proxy, including the `/push/` URL handling.

If you inadvertently set up a more elaborate (traditional) RP setup in front of RP you might be running into some of the problems you've mentioned. Double-check the AIO RP docs.

This isn't a support forum. If you need further assistance, please follow-up at the proper place for that: the Nextcloud Help Forum - https://help.nextcloud.com
