### ISSUE TITLE
notify_push fails parsing unix socket as database host

### ISSUE THREAD

**Issue by jrg1k** [nextcloud/notify_push#384]
notify_push: 0.6.8

Run command:
```
/path/to/bin/notify_push \
    --socket-path /run/php/notify_push.sock \
    --socket-permissions 0660 \
    /path/to/config/config.php
```

Output:
```
Error:   x Failed to parse database configuration: error with configuration: empty host
  |-> error with configuration: empty host
  `-> empty host
  ```

  Nextcloud db config:
  ```
  'dbname' => 'nextcloud',
  'dbhost' => '/run/postgresql',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '<password>',
```
This setup was working until recently. I can't pinpoint exactly which update broke it.

**Comment by teutat3s** [comment]
Might be this change:

`0.6.7`
https://github.com/nextcloud/notify_push/blob/1f07b75d32b9c68f68012bc2e0eba47fb92ac497/src/config/nc.rs#L13

vs `0.6.8`
https://github.com/nextcloud/notify_push/blob/23168cf7180091fdd8c549b97be4a8d2be13c3f1/src/config/nc.rs#L13

**Comment by icewind1991** [comment]
Please try if https://github.com/nextcloud/notify_push/pull/389 fixes the problem for you.

To test: you can get the push server binary for your respective platform from [the github actions](https://github.com/nextcloud/notify_push/actions/runs/7730099626) and replace the one in the bin folder with it.

**Comment by dotlambda** [comment]
> Please try if #389 fixes the problem for you.

Works for me on NixOS.

**Comment by icewind1991** [comment]
fix released with 0.6.9

**Comment by gymnae** [comment]
Could you trigger a build of your docker image for this fix? Thank you :)

**Comment by icewind1991** [comment]
done
