### ISSUE TITLE
Nextcloud AIO - notify_push binary was not found.

### ISSUE THREAD

**Issue by AT-StephenDetomasi** [nextcloud/notify_push#411]
Hi there, Unfortunately having an issue with the notify_push container, and haven't been able to work out why. I have NextCloud AIO upgraded to version 28, all is working except for push.

The error message I see in the logs is as follows:

```
Connection to nextcloud-aio-nextcloud (172.27.0.7) 9001 port [tcp/*] succeeded!
The notify_push binary was not found.
Most likely is DNS resolution not working correctly.
You can try to fix this by configuring a DNS server globally in dockers daemon.json.
See https://dockerlabs.collabnix.com/intermediate/networking/Configuring_DNS.html
Afterwards a restart of docker should automatically resolve this.
Additionally, make sure to disable VPN software that might be running on your server
Also check your firewall if it blocks connections to github
If it should still not work afterwards, feel free to create a new thread at https://github.com/nextcloud/all-in-one/discussions/new?category=questions and post the Nextcloud container logs there.
```

I have already tried manually adding DNS server globally and that has not resolve the issue - in fact it made docker refuse to start, perhaps because I have Portainer managing my docker installation.

Any guidance on how to resolve this issue would be appreciated. Thanks!

**Comment by AT-StephenDetomasi** [comment]
Update: Managed to solve this on my own. No issues with networking, just a strange bug it seems. I tried removing and pulling the container several times with various config changes, but what solved it was to remove the container and purge persistent data. and after letting NextCloud AIO pull / update the container (via the config page on port 8080) it seemed to behave itself finally.

**Comment by joshtrichards** [comment]
> `If it should still not work afterwards, feel free to create a new thread at https://github.com/nextcloud/all-in-one/discussions/new?category=questions and post the Nextcloud container logs there.`

FYI, if this comes up again please utilize the channel noted in the output. AIO uses its own notify_push Docker image so we can't be much help here. And if there are any problems with it, the AIO team will probably want to know. :)
