### ISSUE TITLE
Don't bind on "0.0.0.0" by default.

### ISSUE THREAD

**Issue by meepmeep** [nextcloud/notify_push#42]
Following the Readme page, I set the systemd startup script.
The port could be changed with the PORT env, but not the binded IP address.

By default, it binds 0.0.0.0 which is not a good idea when running on a non-docker environment. 

I tried to find the env variable (BIND, IP, HOST), looked up quickly through the code, but couldn't any thing

```
root@kif:/var/www/nextcloud# netstat -taupen |grep 7867
tcp        0      0 0.0.0.0:7867            0.0.0.0:*               LISTEN      33         254813383  13355/notify_push
```
Could you add a settings to bind a specific IP ?

**Comment by icewind1991** [comment]
0.1.5 comes with an option to change this:

```
BIND=127.0.0.1 notify_push
```

or 

```
notify_push --bind 127.0.0.1
```
