### ISSUE TITLE
Failed to detect app version + "🗴 push server can't connect to the Nextcloud server"

### ISSUE THREAD

**Issue by meepmeep** [nextcloud/notify_push#43]
Recently migrated to nextcloud 21, I'm trying to run this notify_push addon.

- adding the app on nextcloud app store : **OK**
- Setting up and starting the push server : **Almost ok** :
```
root@kif:/var/www/nextcloud# sudo -u www-data /var/www/nextcloud/apps/notify_push/bin/x86_64/notify_push /var/www/nextcloud/config/config.php
[2021-02-25 16:59:26.001486 +01:00] WARN [notify_push] src/lib.rs:131: failed to detect app version app: Response was of incompatible type: "Response type not string compatible." (response was nil)
```
(same thing when started with systemd)

- Setting the reverse proxy with nginx (on subpath  /nextcloud/push) : **Seems ok**

```
        location /nextcloud/push/ {
                proxy_pass http://127.0.0.1:7867/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

```
- Restarting nginx  : **OK**
- Enabling the app : **OK**
- Set the url of the push server : **Failed**

```
root@kif:/var/www/nextcloud# sudo -u www-data php occ notify_push:setup https://my.domain.tld/nextcloud/push/
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
🗴 push server can't connect to the Nextcloud server
```

If I shutdown notify_push, I got a 502 bad gateway,

What am i missing ?

```
client push app store 0.1.4
nextcloud 21
php 7.3.27
debian 10
backend mysql
redis server 5.0.3
```

**Comment by Palerm** [comment]
same here with apache2, but had several error and warnings during download and activating the app

**Comment by escoand** [comment]
There seem to be multiple solutions for that, see:

* https://github.com/nextcloud/docker/issues/1422#issuecomment-785744575
* https://github.com/nextcloud/notify_push/issues/11#issuecomment-786154882

**Comment by Palerm** [comment]
Thanks, but I have no docker configuration.

25.02.2021 22:24:15 escoand <notifications@github.com>:

> There seem to be multiple solutions for that, see:
> 
* > nextcloud/docker#1422 (comment)[https://github.com/nextcloud/docker/issues/1422#issuecomment-785744575]
* > #11 (comment)[https://github.com/nextcloud/notify_push/issues/11#issuecomment-786154882]

**Comment by meepmeep** [comment]
"🗴 push server can't connect to the Nextcloud server" **has been solved** by adding the env variable NEXTCLOUD_URL in the notify_push service file.

```
...
[Service]
Environment = NEXTCLOUD_URL=https://my.domain.tld/nextcloud/
...
```
new error, the trusted proxies :

```
🗴 push server is not a trusted proxy, please add 'a.b.c.d' to the list of trusted proxies or configure any existing reverse proxy to forward the 'x-forwarded-for' send by the push server.
  If you're having issues getting the trusted proxy setup working, you can try bypassing any existing reverse proxy
  in your setup by setting the `NEXTCLOUD_URL` environment variable to point directly to the internal Nextcloud webserver url
  (You will still need the ip address of the push server added as trusted proxy)
```

And my nginx configuration is correct :
```
        location /nextcloud/push/ {
                proxy_pass http://127.0.0.1:7867/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

nextcloud config.php : 
```
  'trusted_proxies' =>
  array (
    0 => 'my.domain.tld',
    1 => '127.0.0.1',
    2 => 'a.b.c.d',
  ),
```

**Comment by meepmeep** [comment]
What I don't get is that nextcloud is not behind a reverse proxy on my system. Only the push app.
Nextcloud is delivered directly by nginx, and push use the classic proxy_pass configuration.

What am I missing there ?

**Comment by icewind1991** [comment]
Can you post your full `config.php` (with passwords redacted)

**Comment by meepmeep** [comment]
Ok, I got it. 
I had 2 trusted_proxies array on the config file. Only the last one was used, and it wasn't containing the correct ip address.

Waiting for upgrade to 0.1.5 for https://github.com/nextcloud/notify_push/issues/42, and everything will be running smoothly.

Thank you :)
