### ISSUE TITLE
Missing release tag for 0.1.5

### ISSUE THREAD

**Issue by alerque** [nextcloud/notify_push#46]
It looks like 9d74cc92a was intended as v0.1.5, but it wasn't tagged (or if it was, the tag wasn't pushed).

**Comment by icewind1991** [comment]
Building the release takes a bit :)

**Comment by alerque** [comment]
Looks like the tag just came through...

**Comment by alerque** [comment]
Roger that. I'm accustomed to automated release pipelines where tags get pushed first and binary release artifacts get attached later ;-)
