### ISSUE TITLE
Is it possible to specify REDIS_URL to use a Redis socket?

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/notify_push#523]
I'm trying to setup notify push with a local Nextcloud and Redis, and using environment variables for parameters (that is, not fetching the Nextcloud config file)

Redis is exposed only on a socket: /var/run/redis/redis-server.sock

Does REDIS_URL support also socket specification?

I'm guessing:

`export REDIS_URL=redis:/<username>:<password>@/var/run/redis/redis-server.sock`

but it doesn't work:

```
Error:   × Invalid REDIS_URL environment variable
  ╰─▶ Missing hostname- InvalidClientConfig
```

**Comment by icewind1991** [comment]
Yes, this is supported, see https://docs.rs/redis/latest/redis/#connection-parameters for the supported url formats
