### ISSUE TITLE
TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given in /server/test/apps/notify_push/lib/SetupWizard.php:84

### ISSUE THREAD

**Issue by nursoda** [nextcloud/notify_push#54]
This reproducibly happens on my Arch server (current) (NC 21.0.0.18, NGINX+PHP 8.0.2(php-fpm), MariaDB) installation (as user http) when trying to follow [instructions to install the files HPB](https://github.com/nextcloud/notify_push/blob/main/README.md):

```
$ php occ app:install notify_push
An unhandled exception has been thrown:
TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given in /server/test/apps/notify_push/lib/SetupWizard.php:84
Stack trace:
#0 /server/test/apps/notify_push/lib/SetupWizard.php(84): substr()
#1 /server/test/apps/notify_push/lib/Migration/Install.php(42): OCA\NotifyPush\SetupWizard->testBinary()
#2 /server/test/lib/private/Repair.php(117): OCA\NotifyPush\Migration\Install->run()
#3 /server/test/lib/private/legacy/OC_App.php(1054): OC\Repair->run()
#4 /server/test/lib/private/Installer.php(175): OC_App::executeRepairSteps()
#5 /server/test/core/Command/App/Install.php(68): OC\Installer->installApp()
#6 /server/test/apps/mail/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute()
#7 /server/test/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#8 /server/test/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#9 /server/test/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#10 /server/test/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#11 /server/test/console.php(100): OC\Console\Application->run()
#12 /server/test/occ(11): require_once('...')
#13 {main}http@server /server/test

$ php occ app:install notify_push
notify_push already installed

$ php occ app:enable notify_push
notify_push 0.1.5 enabled
```

So, it WAS installed the first time – and it works fine. But what error is that? Log says:<details>{"reqId":"[ID]","level":3,"time":"2021-02-28T20:39:45+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"fsockopen(): Unable to connect to localhost:7867 (Connection refused) at /server/test/apps/notify_push/lib/SetupWizard.php#92","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/server/test/apps/notify_push/lib/SetupWizard.php","line":92,"function":"fsockopen"},{"file":"/server/test/apps/notify_push/lib/Command/Setup.php","line":137,"function":"isPortFree","class":"OCA\\NotifyPush\\SetupWizard","type":"->"},{"file":"/server/test/apps/**mail**/vendor/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\NotifyPush\\Command\\Setup","type":"->"},{"file":"/server/test/apps/**mail**/vendor/symfony/console/Application.php","line":971,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/server/test/apps/**mail**/vendor/symfony/console/Application.php","line":290,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/server/test/apps/**mail**/vendor/symfony/console/Application.php","line":166,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/server/test/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/server/test/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/server/test/occ","line":11,"args":["/server/test/console.php"],"function":"require_once"}],"File":"/server/test/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.0.18"}</details>

`var_dump($appVersion); exit;` before line 84 of [SetupWizard.php](https://github.com/nextcloud/notify_push/blob/9dc0ea1838493a6f4ad7514fe84bc5010e1f1f7a/lib/SetupWizard.php#L84) yields `string(5) "0.1.5"`.

This issue initially was reported on [the forum](https://help.nextcloud.com/t/notify-push-installation-error-nc21-files-hpb/109433), reporting here upon request by [kesselb](https://help.nextcloud.com/u/kesselb).

Please elaborate on the CAUSE of this, I've seen similar strange stack traces containing [other app's dependencies](https://github.com/nextcloud/server/issues/24995) in the stack trace.

**Comment by icewind1991** [comment]
Should be fixed with 0.1.6
