### ISSUE TITLE
Redis socket connections not supported?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/notify_push#6]
Hi, 

while testing https://github.com/nextcloud/vm/pull/1817, I've found out that it seems like redis socket connections aren't supported by this app. Could you make it work also with socket connections? (it reports that redis is not configured although it is and also works on this system, afaik.)

This is the part from the config.php file that should be of intest:
```php
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'timeout' => 0.5,
    'dbindex' => 0,
    'password' => 'SECRET',
  ),
```

**Comment by szaimen** [comment]
Also, is this a false positive report? (I am not sure)
```
push server is not a trusted proxy, please add '127.0.0.1' to the list of trusted proxies or conf igure any existing reverse proxy to forward the 'x-forwarded-for' send by the push server.
```

**Comment by icewind1991** [comment]
It *should* work

can you try running the binary with the `LOG=notify_push=trace` environment variable, it will then dump the parsed config it's using

`127.0.0.1` does need to be added to the list of trusted proxies, the setup wizard should take care of that though

**Comment by szaimen** [comment]
Thanks for the help!
I've found the issue:
redis wasn't enabled as php module.
