### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by EWouters** [nextcloud/notify_push#66]
Hi,

Are there any special setup requirements if my server uses multiple domains? E.g. example1.cloud and example2.cloud, can I put both of them in the `NEXTCLOUD_URL` in `/etc/systemd/system/notify_push.service`? Or should I create multiple `/etc/systemd/system/notify_push.service` files for each domain?

**Comment by icewind1991** [comment]
If they are separate instances you need to run multiple instances of notify_push. If it is one instance that can be accessed trough multiple domains then you should run one instance with the `NEXTCLOUD_URL` set to one of the domains.

**Comment by EWouters** [comment]
In my case both domains point to the same NC instance. I used the [test_client](https://github.com/nextcloud/notify_push/suites/2238119085/artifacts/46439773) to verify that clients connecting to either domain received push notifications. Thank you.
