### ISSUE TITLE
Not receiving file updated by others (basic sync function fails)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/notify_push#67]
Since I set up HPB, I don't get modified files pushed on my Arch Laptop (NC Sync Client 3.1.3) if they are changed by other users. Server is Arch/NGINX/PHP-FPM/Redis/notify_push 0.1.6, and I'm using sockets like described [here](https://help.nextcloud.com/t/setting-up-files-high-performance-backend/108651/7). Anyone else experiencing this? How to debug this?

**Comment by alerque** [comment]
Is it possible you have suspended your machine or changed network connections since starting the client? I suspect you might have a case of #53, now being tracked over on the related [desktop client issue](https://github.com/nextcloud/desktop/issues/2983).

**Comment by nursoda** [comment]
Just as you wrote in your [comment](https://github.com/nextcloud/desktop/issues/2983#issuecomment-808853926) there, I also assumed that "force sync" would re-establish the sync. I thought I had seen the issue without suspend in between. I now tried to reproduce it like that and couldn't. So even if there remains a suspend-independent issue, we should solve the suspend issue first and re-test after that. That is why I close (and in such case reopen) the issue.
