### ISSUE TITLE
Not a trusted proxy with apache (fix included)

### ISSUE THREAD

**Issue by GieltjE** [nextcloud/notify_push#68]
Load the mod_remoteip.so module and add the following config:
```
RemoteIPHeader X-Forwarded-For
```

**Comment by eibex** [comment]
Shouldn't you add trusted proxies for security?
```
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy cloud.example.com
RemoteIPTrustedProxy 11.22.33.44
```

**Comment by GieltjE** [comment]
That way nextcloud gives a warning that anyone could fake their IP, don't know if my solution technically fixes that, but at least it's quiet.

**Comment by eibex** [comment]
@icewind1991 is there any reason this is not in the README under the Apache2 section? I cannot setup the push server properly without this setting.

By setting this no trusted proxies need to be set whatsoever in config.php (apache2 virtualhost). Is it safe?

Without this setting the setup complains that my server's public IP isn't a trusted proxy (I am not running Nextcloud behind a reverse proxy or Cloudflare, the proxy is set up only for notify_push).

**Comment by juliusbr** [comment]
I've also added RemoteIPTrustedProxy  to the Apache config, as described here. https://help.nextcloud.com/t/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/108633/5

No warnings from Nextcloud, so I guess this configuration is safer?

**Comment by zenlord** [comment]
Check your config.php for duplicate 'trusted_proxies' entries. I encountered a similar issue, and initially fixed it with the remoteip module. Later I discovered that somehow a second trusted_proxies entry was overriding my manual setting, and once I merged both entries, I no longer needed the remoteip apache module and the additional settings.

**Comment by icewind1991** [comment]
having apache handle the forwarded-for headers is not the recommend approach and doing it without specifying the trusted proxies is insecure.

If you're having issues with the trusted proxies error when provide the details in #11 (using the latest version as it adds additional diagnostics)
