### ISSUE TITLE
Minimum System Requirements?

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notify_push#7]
Hi, wondering what the minimum system requirements are.

- Is notify_push the complete Files HPB?
- Will this be supported on aarch64 and armv8 Raspberry Pi devices with 1 - 8gb ram?

Thanks!

**Comment by szaimen** [comment]
> is notify_push the complete Files HPB?

Yes, afaik.

> Will this be supported on aarch64 and armv8 Raspberry Pi devices with 1 - 8gb ram?

As far as I can see it is available for
armv7, aarch64 and x86_64
https://github.com/nextcloud/notify_push/blob/96a46920a304529edc974236ae2a0ea52ac5ac26/krankerl.toml#L3-L5

**Comment by icewind1991** [comment]
The distributed packages comes with the binaries for armv7, aarch64 and x86_64 and work on the pi 3 and 4, other architectures *might* work if you compile the binary yourself.
