### ISSUE TITLE
How to set this up with Docker

### ISSUE THREAD

**Issue by ntimo** [nextcloud/notify_push#8]
Hello,

I am using the officual Nextcloud 21 docker image to run Nextcloud and now I am wondering how I can setup this new high performance backend for the docker Installation of Nextcloud. Do you have any guidance? 

Thanks :)

**Comment by raimund-schluessler** [comment]
I would propose to track this issue in the docker repository, since it fits better there, see https://github.com/nextcloud/docker/issues/1422
