### ISSUE TITLE
Failed to connect to Nextcloud database

### ISSUE THREAD

**Issue by tfvlrue** [nextcloud/notify_push#83]
Hi,
I just upgraded to Nextcloud 21 and trying to get notify_push up and running. Running on FreeBSD 12.2 and built the binary locally. Using HTTPS certificate from Let's Encrypt. However, notify_push fails to connect to my Nextcloud instance when I run it.

```
www@server:~ % /var/www/nextcloud/apps/notify_push/bin/amd64/notify_push /var/www/nextcloud/config/config.php
[2021-04-16 00:22:38.494793 -04:00] WARN [rustls::session] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.0/src/session.rs:798: Sending fatal alert DecodeError
Error:
   0: Failed to connect to Nextcloud database
   1: error communicating with the server: invalid certificate: BadDER
   2: invalid certificate: BadDER

Location:
   /root/nextcloud_notify_push/src/storage_mapping.rs:57

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::hb303c81a7d5b7c79
      at <unknown source file>:<unknown line>
   2: <E as eyre::context::ext::StdError>::ext_report::h4685d8b635fbda84
      at <unknown source file>:<unknown line>
   3: notify_push::main::{{closure}}::he27b08b64116f0f1
      at <unknown source file>:<unknown line>
   4: notify_push::main::hbcac0d378388707c
      at <unknown source file>:<unknown line>
   5: std::sys_common::backtrace::__rust_begin_short_backtrace::h261dfd1702e70c3e
      at <unknown source file>:<unknown line>
   6: main<unknown>
      at <unknown source file>:<unknown line>
   7: _start<unknown>
      at /usr/src/lib/csu/amd64/crt1.c:76
```

I'm just passing in the same config that the Nextcloud instance is using, and it's all pretty bog standard, I think. Here's a snippet of the config with sensitive bits redacted:

```
$CONFIG = array (
...
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'default_phone_region' => 'US',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'memcache.locking' => '\OC\Memcache\Redis',
  'memcache.distributed' => '\OC\Memcache\Redis',
  'redis' => [
    'host'     => '/tmp/redis.sock',
    'port'     => 0,
    'dbindex'  => 0,
    'password' => 'xxx',
    'timeout'  => 1.5,
  ],
...
);
```

You can see I'm using a locally hosted instance of MySQL for the database. If I temporarily stop the MySQL service, notify_push hangs on launch, telling me there is at least some database network request reaching it.

I'm not sure how to further debug this, so any help would be appreciated. Thanks!

**Comment by icewind1991** [comment]
Can you run the binary with `--dump-config` and post the output

**Comment by icewind1991** [comment]
Additionally, can you try switching from `localhost` to `127.0.0.1` to cause it to use TCP instead of a unix socket

**Comment by ebiagi** [comment]
Hello, trying to connect to the mariadb instance which in my case is on another machine in another subnet, gives me the same error.
The connection between the nextcloud server and the nextcloud db is encrypted, here's my config.php snippet: 

```
 'dbname' => 'nextcloud',
  'dbhost' => 'tsrv01:3306',
  'dbdriveroptions' =>
  array (
    1007 => '/etc/mysql/ssl/client-key.pem',
    1008 => '/etc/mysql/ssl/client-cert.pem',
    1009 => '/etc/mysql/ssl/ca_cert.pem',
    1014 => 'false',
  ),
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'PASSWORD',
```

I’ve tried to add some environment variables (including the ALLOW_SELF_SIGNED=true / --allow-self-signed) to my systemd unit file but still no luck.
The only thing that worked is to comment out the dbdriveroptions array section, which sets the encription certificates used to connect, but I do not want to disable ssl encryption.

Running the binary gives me the following output

```
[2021-04-16 16:46:28.737673 +02:00] WARN [rustls::session] /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.0/src/session.rs:798: Sending fatal alert DecodeError
Error:
   0: Failed to connect to Nextcloud database
   1: error communicating with the server: invalid certificate: BadDER
   2: invalid certificate: BadDER

Location:
   /tmp/krankerl.PNFmShx8gZmS/notify_push/src/storage_mapping.rs:57

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```


while this is the output with --dump-config gives

```
Config {
    database: AnyConnectOptions(
        MySql(
            MySqlConnectOptions {
                host: "tsrv01",
                port: 3306,
                socket: None,
                username: "nextcloud",
                password: Some(
                    "SECRETPASSWORD",
                ),
                database: Some(
                    "nextcloud",
                ),
                ssl_mode: Preferred,
                ssl_ca: None,
                statement_cache_capacity: 100,
                charset: "utf8mb4",
                collation: None,
                log_settings: LogSettings {
                    statements_level: Info,
                    slow_statements_level: Warn,
                    slow_statements_duration: 1s,
                },
            },
        ),
    ),
    database_prefix: "oc_",
    redis: [
        ConnectionInfo {
            addr: Unix(
                "/var/run/redis/redis-server.sock",
            ),
            db: 0,
            username: None,
            passwd: None,
        },
    ],
    nextcloud_url: "https://XXX.XX.XX/",
    metrics_bind: None,
    log_level: "warn",
    bind: Tcp(
        0.0.0.0:7867,
    ),
    allow_self_signed: false,
}
```

**Comment by tfvlrue** [comment]
> Can you run the binary with `--dump-config` and post the output
> Additionally, can you try switching from `localhost` to `127.0.0.1` to cause it to use TCP instead of a unix socket

Switching the database host to 127.0.01 results in a similar error:

```
Error:
   0: Failed to connect to Nextcloud database
   1: error occurred while attempting to establish a TLS connection: InvalidDNSN                                                                                                                               ameError
   2: InvalidDNSNameError

Location:
   /root/nextcloud_notify_push/src/storage_mapping.rs:57
```

Here is the sanitized output from --dump-config, first with localhost, second with 127.0.0.1

```
Config {
    database: AnyConnectOptions(
        MySql(
            MySqlConnectOptions {
                host: "localhost",
                port: 3306,
                socket: Some(
                    "/tmp/mysql.sock",
                ),
                username: "",
                password: Some(
                    "",
                ),
                database: Some(
                    "",
                ),
                ssl_mode: Preferred,
                ssl_ca: None,
                statement_cache_capacity: 100,
                charset: "utf8mb4",
                collation: None,
                log_settings: LogSettings {
                    statements_level: Info,
                    slow_statements_level: Warn,
                    slow_statements_duration: 1s,
                },
            },
        ),
    ),
    database_prefix: "oc_",
    redis: [
        ConnectionInfo {
            addr: Unix(
                "/tmp/redis.sock",
            ),
            db: 0,
            username: None,
            passwd: Some(
                "",
            ),
        },
    ],
    nextcloud_url: "https://subdomain.domain.com/",
    metrics_bind: None,
    log_level: "warn",
    bind: Tcp(
        0.0.0.0:7867,
    ),
    allow_self_signed: false,
}
```

```
Config {
    database: AnyConnectOptions(
        MySql(
            MySqlConnectOptions {
                host: "127.0.0.1",
                port: 3306,
                socket: None,
                username: "",
                password: Some(
                    "",
                ),
                database: Some(
                    "",
                ),
                ssl_mode: Preferred,
                ssl_ca: None,
                statement_cache_capacity: 100,
                charset: "utf8mb4",
                collation: None,
                log_settings: LogSettings {
                    statements_level: Info,
                    slow_statements_level: Warn,
                    slow_statements_duration: 1s,
                },
            },
        ),
    ),
    database_prefix: "oc_",
    redis: [
        ConnectionInfo {
            addr: Unix(
                "/tmp/redis.sock",
            ),
            db: 0,
            username: None,
            passwd: Some(
                "",
            ),
        },
    ],
    nextcloud_url: "https://subdomain.domain.com/",
    metrics_bind: None,
    log_level: "warn",
    bind: Tcp(
        0.0.0.0:7867,
    ),
    allow_self_signed: false,
}
```

**Comment by thstyl2000** [comment]
Sorry for bumping, did you manage to connect?

**Comment by tfvlrue** [comment]
> Sorry for bumping, did you manage to connect?

No luck here. I'm open to suggestions for other things to try. Also curious if anyone has successfully gotten this working with MySQL or MariaDB.

**Comment by icewind1991** [comment]
Can you test if the binaries from https://github.com/nextcloud/notify_push/actions/runs/793350027 solve this issue for you.

You can place the binary for your platform into the relevant `nextcloud/apps/notify_push/bin/...` folder and rename it to overwrite the existing `notify_push` binary to install it.

**Comment by tfvlrue** [comment]
> Can you test if the binaries from https://github.com/nextcloud/notify_push/actions/runs/793350027 solve this issue for you.
> 
> You can place the binary for your platform into the relevant `nextcloud/apps/notify_push/bin/...` folder and rename it to overwrite the existing `notify_push` binary to install it.

Can do! For anyone else trying this one FreeBSD, I had to:
```
kldload linux64
sudo brandelf -t linux ./notify_push
```
...to get it to run the Linux executable.

Looks like it's running now! `http://myserver:7867/` produces a 404 response.

However, now I'm running into an issue running
```
occ notify_push:setup https://myserver.com/push
```
It fails with:
```
✓ redis is configured
🗴 push server is not receiving redis messages (received 478553865, got 0)
```
I confirmed the local redis instance is working fine (using redis-cli and listing keys), so I'm not sure how to interpret this error. The large number after "received" seems to increase every time I run the command. What does it mean?

I assume this is why test_client fails with this:
```
Error:
   0: notify_push app doesn't seem to be enabled or setup

Location:
   test_client/src/main.rs:87
```

**Comment by icewind1991** [comment]
please run the push binary with `LOG=DEBUG` and provide the output of the binary while trying to run the setup

**Comment by tfvlrue** [comment]
> please run the push binary with `LOG=DEBUG` and provide the output of the binary while trying to run the setup

There is a lot of debug output when first starting notify_push with LOG=DEBUG. I can post that if you would find it helpful, but nothing stood out to me as particularly interesting there.

This is what notify_push logs when I run the setup command:
```
[2021-04-29 22:26:48.906982 -04:00] DEBUG [notify_push] src/lib.rs:399: Received test cookie 717137968
```
The number printed there matches the one in the error output from the command itself:
```
🗴 push server is not receiving redis messages (received 717137968, got 0)
```

**Comment by mdoggydog** [comment]
> Can you test if the binaries from https://github.com/nextcloud/notify_push/actions/runs/793350027 solve this issue for you.

I am getting a similar "Failed to connect to Nextcloud database" error, with both the above binary and the appstore binary. However, in my case, I am connecting to a Postgresql database via `'dbhost' => '127.0.0.1'`:
```
Error: 
   0: Failed to connect to Nextcloud database
   1: error occurred while attempting to establish a TLS connection: InvalidDNSNameError
   2: InvalidDNSNameError
```
The postgresql log also corroborates this, complaining `could not accept SSL connection`.

Seems like the same fix that was applied to mysql connections also needs to be applied to pgsql connections.

**Comment by icewind1991** [comment]
@mdoggydog please try the binaries from https://github.com/nextcloud/notify_push/actions/runs/942695192

**Comment by tfvlrue** [comment]
Since my original database-related problem has been resolved, I'm closing this issue.

Strangely, after pulling latest and building, the redis problem I mentioned above stopped happening. Everything seems to be working now, confirmed by running test_client.

Thanks all!

**Comment by mdoggydog** [comment]
> @mdoggydog please try the binaries from https://github.com/nextcloud/notify_push/actions/runs/942695192

@icewind1991, Yes, that appears to have solved the database connection issue, thanks!

(`occ notify_push:setup` is now complaining
```
             🗴 push server can't connect to the Nextcloud server
               Response from nextcloud is not a number: invalid digit found in string
```
but I figure that is some other problem altogether...)
