### ISSUE TITLE
Please add a --no-ansi switch to suppress ANSI sequences on the output

### ISSUE THREAD

**Issue by j-ed** [nextcloud/notify_push#84]
For logging/debug purposes I've redirected the program output to a log file. Unfortunately it currently logs all ANSI sequences to the file too, which makes it difficult to read on the console or to automatically analyze its content. It would be good to have a "**--no-ansi**" command line switch, similar to the occ command, to suppress all ANSI sequences by default.

**Comment by alerque** [comment]
This can be achieved a bit easier and pretty reliably by detecting whether the output is a terminal or a redirect/file. I'm sure there is a Rust library that takes care of the mechanics, *lots* of apps do this with pretty high reliability so it must not be too hard.
