### ISSUE TITLE
`*.config.php` files not read in addition to `config.php`

### ISSUE THREAD

**Issue by acsfer** [nextcloud/notify_push#88]
After run it for several days, today, I got this error from the `syslog`.
Nextcloud 21.0.1, notify_push 0.1.7.

> ERROR [notify_push] src/lib.rs:154: Failed to load storage mapping from database: error communicating with the server:
No such file or directory (os error 2): No such file or directory (os error 2)

### config.php

```
  'trusted_proxies' =>
  array (
    0 => '127.0.0.1',
    1 => '::1',
    2 => '2001:bc8:3534::1',
  ),
  'datadirectory' => '/srv/users/nextcloud/data',
  'tempdirectory' => '/srv/users/nextcloud/tmp',
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'overwrite.cli.url' => 'https://my.nextcloud.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'mysql.db1',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxx',
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'dbindex' => 11,
    'timeout' => 0,
  ),
```

### mysql.config.php
`'dbhost' => 'mysql.db2',`

**Comment by acsfer** [comment]
Ok i got it; database host was moved, and a file `mysql.config.php` is present in adition to `config.php`. This file is not read apparently, and it should as the server does; the trace below shows it tries to connect to the MySQL configured at `config.php` and not the (good) one configured at `mysql.config.php` 

```
Error:
   0: Failed to connect to Nextcloud database
   1: error returned from database: 1045 (28000): Access denied for user 'nextcloud'@'10.91.156.59' (using password: YES)
```

**Comment by Starbix** [comment]
Would it be possible to add an option for reading `*.config.php`? My setup is based on the official docker container which contains the following config files: https://github.com/nextcloud/docker/tree/master/.config
`notify_push` fails to parse these file, eg. [the apps config file](https://github.com/nextcloud/docker/blob/master/.config/apps.config.php) where I get this:
```Error:
   0: Failed to parse config
   1: Failed to parse nextcloud config
   2: Error while parsing php literal:
   2: . |
   2: 2 |   'apps_paths' => array (
   2: 3 |       0 => array (
   2: 4 |               'path'     => OC::$SERVERROOT.'/apps',
   2:   |                             ^^ No valid token found, expected one of [Bool, Integer, Float, LiteralString, Null, Array, SquareOpen]
   2: 5 |               'url'      => '/apps',
   2: 6 |               'writable' => false,
   2:
```

**Comment by unixfy** [comment]
I ended up solving this by removing the config file argument from the notify_push container's entrypoint and setting the necessary config parameters through environment variables. It's messy but it works

**Comment by icewind1991** [comment]
With 0.2.1 this option is disabled by default, to enable it use the `--glob-config` option
