### ISSUE TITLE
Why a websocket server?

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/notify_push#92]
Since the objective is to push messages from the server to the client, I'd like to understand the rationale for using websockets, which requires an additional server daemon and dramatically complicates the configuration requirements, when the same can be achieved using SSE, which is trivial to implement in a php script?

**Comment by icewind1991** [comment]
"not using php" isn't a cause of "using websockets", "using websockets" is a cause of "not using php".

php isn't great for long running processes, and a long running php process for every client on the instance is bound to blow up as the instance scales up. So using php for this was never really an option with the problem this is trying to solve.

Once there is no longer the requirement of using php, websockets seemed like the most obvious protocol to use.

**Comment by lbdroid** [comment]
Could you clarify? You've made some claims regarding the suitability of php for handling a large number of long running processes, but I've not been able to find anything to substantiate your claims.

In particular, your second paragraph, in its entirety. Is this something you know through empirical testing? If so, could you provide the details of this testing? If not, is this characteristic documented somewhere? A link to a reference would be sufficient so that I can investigate the validity of such claims.

Thanks.

**Comment by lbdroid** [comment]
Being mono-directional isn't an issue since the server is always reachable and doesn't need to maintain an open connection to receive messages from the client, and the scaling issue only applies to HTTP/1.1, not HTTP/2.

And once again, I'm seeing claims of "would be problematic to deploy", "enormously problematic", etc., without anything backing it up. WHY do you think these would be problematic? Right now, I don't see anything backing up these claims, so I can't take them seriously and am forced to believe these claims are tied to a misconception rather than being representative of technical limitation.

**Comment by lbdroid** [comment]
I guess I shouldn't have mentioned php, since you're now fixated on it. I only mentioned it as an example of how trivial it is to implement SSE.

I get the objective of scalability in large deployments, but at the same time, it seems shortsighted to limit it to that, when you would likely make a bigger impact by lowering the barrier to entry and expanding the target to include pushing notifications to mobile devices -- nextcloud still does not have a decent solution to that, since it is only able to push truncated messages (200 character limit) through FCM (an untrusted 3rd party service) using a propetary intermediary.

**Comment by alerque** [comment]
I'm sure if you build a working implementation of push to mobile without the app running I'm sure there would be plenty of interest in using it. In the mean time I don't understand why you're knocking on an implementation clearly well suited to the target use case for not having a different target in mind.

**Comment by lbdroid** [comment]
Its not that at all. The issue is actually about efficiency and component reuse. It isn't efficient to build and maintain a dozen implementations of things that are very nearly the same, when the alternative is to build one thing to address a dozen use cases. Saves a lot of work to do a little more planning at the start.

**Comment by lbdroid** [comment]
Also @icewind1991 ;
You mention 8mb per php process, is that 8 *additional* mb per process? Or are you taking something like the resident set size that includes all of the shared libraries that are in common between the several processes?

This is an important distinction, because you can fork a process with an RSS of 1 GB a thousand times into a thousand processes with each an RSS of 1 GB, and still only have ~1 GB of memory in use. While obviously it will be slightly less efficient to fork processes as in php than to use pthreads, i dont think it would be nearly as severe as you imply.
