### ISSUE TITLE
Suitability for mobile push-messaging?

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/notify_push#94]
I haven't looked at the backend implementation in great detail yet, however (somebody correct me if I'm wrong), it appears that the server implementation is bound to a single instance of nextcloud, therefore if this were to be used for pushing notifications to a mobile device, each nextcloud instance, even in circumstances where multiple instances were run on a single physical server, would require a separate persistent connection from the client, whereas using the push-proxy approach (described here: https://github.com/nextcloud/notifications/blob/master/docs/push-v2.md) allows multiple nextcloud instances to be served via a single push proxy and therefore single connection.

Is there anything that notify_push actually does that can't be done using a push proxy?
Is there any intention to enhance notify_push so that a single instance can be shared among multiple instances of nextcloud?

**Comment by szaimen** [comment]
Hi, please see https://github.com/nextcloud/talk-android/issues/1008
